// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const DnsRecordType = {
    /**
     * IPv4 address record.
     */
    A: "A",
    /**
     * IPv6 address record.
     */
    Aaaa: "AAAA",
    /**
     * Canonical name (alias) record.
     */
    Cname: "CNAME",
    /**
     * Mail exchange record.
     */
    Mx: "MX",
    /**
     * Name server record.
     */
    Ns: "NS",
    /**
     * Pointer (reverse DNS) record.
     */
    Ptr: "PTR",
    /**
     * Start of authority record.
     */
    Soa: "SOA",
    /**
     * Service locator record.
     */
    Srv: "SRV",
    /**
     * Arbitrary text record.
     */
    Txt: "TXT",
} as const;

export type DnsRecordType = (typeof DnsRecordType)[keyof typeof DnsRecordType];

export const FirewallGroupType = {
    /**
     * Group of IPv4 addresses or CIDRs.
     */
    AddressGroup: "address-group",
    /**
     * Group of port numbers or ranges.
     */
    PortGroup: "port-group",
    /**
     * Group of IPv6 addresses or CIDRs.
     */
    Ipv6AddressGroup: "ipv6-address-group",
} as const;

export type FirewallGroupType = (typeof FirewallGroupType)[keyof typeof FirewallGroupType];

export const FirewallZonePolicyAction = {
    /**
     * Permit matching traffic.
     */
    Allow: "ALLOW",
    /**
     * Silently drop matching traffic.
     */
    Block: "BLOCK",
    /**
     * Drop matching traffic and send a rejection response.
     */
    Reject: "REJECT",
} as const;

export type FirewallZonePolicyAction = (typeof FirewallZonePolicyAction)[keyof typeof FirewallZonePolicyAction];

export const FirewallZonePolicyConnectionStateType = {
    /**
     * Match all connection states.
     */
    All: "ALL",
    /**
     * Match only return (responding) traffic.
     */
    RespondOnly: "RESPOND_ONLY",
    /**
     * Match the explicit connection states listed in connectionStates.
     */
    Custom: "CUSTOM",
} as const;

export type FirewallZonePolicyConnectionStateType = (typeof FirewallZonePolicyConnectionStateType)[keyof typeof FirewallZonePolicyConnectionStateType];

export const FirewallZonePolicyIpVersion = {
    /**
     * Match both IPv4 and IPv6 traffic.
     */
    Both: "BOTH",
    /**
     * Match IPv4 traffic only.
     */
    Ipv4: "IPV4",
    /**
     * Match IPv6 traffic only.
     */
    Ipv6: "IPV6",
} as const;

export type FirewallZonePolicyIpVersion = (typeof FirewallZonePolicyIpVersion)[keyof typeof FirewallZonePolicyIpVersion];

export const PortForwardProtocol = {
    /**
     * Match both TCP and UDP traffic.
     */
    TcpUdp: "tcp_udp",
    /**
     * Match TCP traffic only.
     */
    Tcp: "tcp",
    /**
     * Match UDP traffic only.
     */
    Udp: "udp",
} as const;

export type PortForwardProtocol = (typeof PortForwardProtocol)[keyof typeof PortForwardProtocol];

export const VlanPurpose = {
    /**
     * Routed LAN/VLAN network.
     */
    Corporate: "corporate",
    /**
     * Guest network with isolation/portal.
     */
    Guest: "guest",
    /**
     * Layer-2 VLAN with no gateway.
     */
    VlanOnly: "vlan-only",
    /**
     * WAN uplink network.
     */
    Wan: "wan",
    /**
     * Remote-user VPN server network.
     */
    RemoteUserVpn: "remote-user-vpn",
    /**
     * Site-to-site VPN network.
     */
    SiteVpn: "site-vpn",
    /**
     * VPN client network.
     */
    VpnClient: "vpn-client",
} as const;

export type VlanPurpose = (typeof VlanPurpose)[keyof typeof VlanPurpose];

export const WlanSecurity = {
    /**
     * Open network with no authentication.
     */
    Open: "open",
    /**
     * WPA personal with a pre-shared key.
     */
    WpaPsk: "wpapsk",
    /**
     * WPA enterprise with RADIUS/802.1X (EAP).
     */
    WpaEap: "wpaeap",
    /**
     * Legacy WEP encryption.
     */
    Wep: "wep",
    /**
     * OSU Server-only authenticated L2 encryption (Hotspot 2.0).
     */
    Osen: "osen",
} as const;

export type WlanSecurity = (typeof WlanSecurity)[keyof typeof WlanSecurity];
