version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gosec
    - misspell

formatters:
  enable:
    - gofmt
    - goimports
