// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("unifi");

/**
 * UniFi OS local API key. Preferred for headless automation. Mutually exclusive with username/password.
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey");
    },
    enumerable: true,
});

/**
 * Skip TLS certificate verification (for self-signed controller certs).
 */
export declare const insecureTls: boolean | undefined;
Object.defineProperty(exports, "insecureTls", {
    get() {
        return __config.getObject<boolean>("insecureTls");
    },
    enumerable: true,
});

/**
 * Local admin password.
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * UniFi site name (defaults to "default").
 */
export declare const site: string | undefined;
Object.defineProperty(exports, "site", {
    get() {
        return __config.get("site");
    },
    enumerable: true,
});

/**
 * Base URL of the UniFi controller, e.g. https://192.168.1.1 (omit any /api suffix).
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url");
    },
    enumerable: true,
});

/**
 * Local admin username. Use with password when not using an API key.
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

