// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace network {
    export interface DeviceDot1xArgs {
        fallbackNetworkId?: pulumi.Input<string | undefined>;
        portControlEnabled?: pulumi.Input<boolean | undefined>;
    }

    export interface DeviceEtherLightingArgsArgs {
        behavior?: pulumi.Input<string | undefined>;
        brightness?: pulumi.Input<number | undefined>;
        ledMode?: pulumi.Input<string | undefined>;
        mode?: pulumi.Input<string | undefined>;
    }

    export interface DeviceEthernetOverrideArgs {
        ifname: pulumi.Input<string>;
        networkGroup?: pulumi.Input<string | undefined>;
    }

    export interface DeviceLcmArgs {
        brightness?: pulumi.Input<number | undefined>;
        idleTimeout?: pulumi.Input<number | undefined>;
        nightModeBegins?: pulumi.Input<string | undefined>;
        nightModeEnds?: pulumi.Input<string | undefined>;
        orientationOverride?: pulumi.Input<number | undefined>;
    }

    export interface DeviceLedArgs {
        etherLighting?: pulumi.Input<inputs.network.DeviceEtherLightingArgsArgs | undefined>;
        override?: pulumi.Input<string | undefined>;
        overrideColor?: pulumi.Input<string | undefined>;
        overrideColorBrightness?: pulumi.Input<number | undefined>;
    }

    export interface DeviceOutletArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        overrides?: pulumi.Input<pulumi.Input<inputs.network.DeviceOutletOverrideArgs>[] | undefined>;
        powerCycleEnabled?: pulumi.Input<boolean | undefined>;
    }

    export interface DeviceOutletOverrideArgs {
        cycleEnabled?: pulumi.Input<boolean | undefined>;
        index: pulumi.Input<number>;
        name?: pulumi.Input<string | undefined>;
        relayState?: pulumi.Input<boolean | undefined>;
    }

    export interface DevicePortOverrideArgs {
        aggregateNumPorts?: pulumi.Input<number | undefined>;
        autoneg?: pulumi.Input<boolean | undefined>;
        dot1xCtrl?: pulumi.Input<string | undefined>;
        dot1xIdleTimeout?: pulumi.Input<number | undefined>;
        egressRateLimitKbps?: pulumi.Input<number | undefined>;
        egressRateLimitKbpsEnabled?: pulumi.Input<boolean | undefined>;
        excludedNetworkIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        fecMode?: pulumi.Input<string | undefined>;
        forward?: pulumi.Input<string | undefined>;
        fullDuplex?: pulumi.Input<boolean | undefined>;
        isolation?: pulumi.Input<boolean | undefined>;
        lldpmedEnabled?: pulumi.Input<boolean | undefined>;
        lldpmedNotifyEnabled?: pulumi.Input<boolean | undefined>;
        mirrorPortIdx?: pulumi.Input<number | undefined>;
        name?: pulumi.Input<string | undefined>;
        nativeNetworkId?: pulumi.Input<string | undefined>;
        opMode?: pulumi.Input<string | undefined>;
        poeMode?: pulumi.Input<string | undefined>;
        portIdx: pulumi.Input<number>;
        portKeepaliveEnabled?: pulumi.Input<boolean | undefined>;
        portProfileId?: pulumi.Input<string | undefined>;
        portSecurityEnabled?: pulumi.Input<boolean | undefined>;
        portSecurityMacAddress?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        priorityQueue1Level?: pulumi.Input<number | undefined>;
        priorityQueue2Level?: pulumi.Input<number | undefined>;
        priorityQueue3Level?: pulumi.Input<number | undefined>;
        priorityQueue4Level?: pulumi.Input<number | undefined>;
        settingPreference?: pulumi.Input<string | undefined>;
        speed?: pulumi.Input<number | undefined>;
        stormctrlBroadcastEnabled?: pulumi.Input<boolean | undefined>;
        stormctrlBroadcastLevel?: pulumi.Input<number | undefined>;
        stormctrlBroadcastRate?: pulumi.Input<number | undefined>;
        stormctrlMcastEnabled?: pulumi.Input<boolean | undefined>;
        stormctrlMcastLevel?: pulumi.Input<number | undefined>;
        stormctrlMcastRate?: pulumi.Input<number | undefined>;
        stormctrlType?: pulumi.Input<string | undefined>;
        stormctrlUcastEnabled?: pulumi.Input<boolean | undefined>;
        stormctrlUcastLevel?: pulumi.Input<number | undefined>;
        stormctrlUcastRate?: pulumi.Input<number | undefined>;
        stpPortMode?: pulumi.Input<boolean | undefined>;
        taggedVlanMgmt?: pulumi.Input<string | undefined>;
        voiceNetworkId?: pulumi.Input<string | undefined>;
    }

    export interface DeviceRadioOverrideArgs {
        antennaGain?: pulumi.Input<number | undefined>;
        channel?: pulumi.Input<string | undefined>;
        channelWidth?: pulumi.Input<number | undefined>;
        minRssi?: pulumi.Input<number | undefined>;
        minRssiEnabled?: pulumi.Input<boolean | undefined>;
        name?: pulumi.Input<string | undefined>;
        radio: pulumi.Input<string>;
        txPower?: pulumi.Input<string | undefined>;
        txPowerMode?: pulumi.Input<string | undefined>;
    }

    export interface DeviceSnmpArgs {
        contact?: pulumi.Input<string | undefined>;
        location?: pulumi.Input<string | undefined>;
    }

    export interface DeviceStpArgs {
        priority?: pulumi.Input<string | undefined>;
        version?: pulumi.Input<string | undefined>;
    }

    export interface DeviceSwitchingArgs {
        flowControlEnabled?: pulumi.Input<boolean | undefined>;
        jumboFrameEnabled?: pulumi.Input<boolean | undefined>;
        poeMode?: pulumi.Input<string | undefined>;
        vlanEnabled?: pulumi.Input<boolean | undefined>;
    }

    export interface DeviceVrrpArgs {
        mode?: pulumi.Input<string | undefined>;
        priority?: pulumi.Input<number | undefined>;
    }

    export interface FirewallRuleConnectionStateArgs {
        established?: pulumi.Input<boolean | undefined>;
        invalid?: pulumi.Input<boolean | undefined>;
        new?: pulumi.Input<boolean | undefined>;
        related?: pulumi.Input<boolean | undefined>;
    }

    export interface FirewallRuleDestinationArgs {
        address?: pulumi.Input<string | undefined>;
        addressIpv6?: pulumi.Input<string | undefined>;
        firewallGroupIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        networkId?: pulumi.Input<string | undefined>;
        networkType?: pulumi.Input<string | undefined>;
        port?: pulumi.Input<string | undefined>;
    }

    export interface FirewallRuleProtocolMatchArgs {
        icmpTypename?: pulumi.Input<string | undefined>;
        icmpv6Typename?: pulumi.Input<string | undefined>;
        matchExcepted?: pulumi.Input<boolean | undefined>;
        protocol?: pulumi.Input<string | undefined>;
        protocolV6?: pulumi.Input<string | undefined>;
    }

    export interface FirewallRuleSourceArgs {
        address?: pulumi.Input<string | undefined>;
        addressIpv6?: pulumi.Input<string | undefined>;
        firewallGroupIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        mac?: pulumi.Input<string | undefined>;
        networkId?: pulumi.Input<string | undefined>;
        networkType?: pulumi.Input<string | undefined>;
        port?: pulumi.Input<string | undefined>;
    }

    export interface FirewallZonePolicyDestinationArgsArgs {
        appCategoryIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        appIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        ipGroupId?: pulumi.Input<string | undefined>;
        ips?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        matchOppositeIps?: pulumi.Input<boolean | undefined>;
        matchOppositePorts?: pulumi.Input<boolean | undefined>;
        /**
         * What the destination matches: ANY | APP | APP_CATEGORY | IP | REGION | WEB.
         */
        matchingTarget?: pulumi.Input<string | undefined>;
        /**
         * Refines the destination match: ANY | OBJECT (saved group) | SPECIFIC (inline values).
         */
        matchingTargetType?: pulumi.Input<string | undefined>;
        port?: pulumi.Input<string | undefined>;
        portGroupId?: pulumi.Input<string | undefined>;
        portMatchingType?: pulumi.Input<string | undefined>;
        regions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        webDomains?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        zoneId: pulumi.Input<string>;
    }

    export interface FirewallZonePolicyMatchingArgsArgs {
        /**
         * Connection-state matching: ALL | RESPOND_ONLY | CUSTOM.
         */
        connectionStateType?: pulumi.Input<string | undefined>;
        connectionStates?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        /**
         * L3 version the policy matches: BOTH | IPV4 | IPV6.
         */
        ipVersion?: pulumi.Input<string | undefined>;
        matchIpSec?: pulumi.Input<boolean | undefined>;
        /**
         * IPsec matching mode: MATCH_IP_SEC | MATCH_NON_IP_SEC.
         */
        matchIpSecType?: pulumi.Input<string | undefined>;
        matchOppositeProtocol?: pulumi.Input<boolean | undefined>;
        protocol?: pulumi.Input<string | undefined>;
    }

    export interface FirewallZonePolicyScheduleArgsArgs {
        date?: pulumi.Input<string | undefined>;
        dateEnd?: pulumi.Input<string | undefined>;
        dateStart?: pulumi.Input<string | undefined>;
        /**
         * Schedule pattern: ALWAYS | EVERY_DAY | EVERY_WEEK | ONE_TIME_ONLY | CUSTOM.
         */
        mode?: pulumi.Input<string | undefined>;
        repeatOnDays?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        timeAllDay?: pulumi.Input<boolean | undefined>;
        timeRangeEnd?: pulumi.Input<string | undefined>;
        timeRangeStart?: pulumi.Input<string | undefined>;
    }

    export interface FirewallZonePolicySourceArgsArgs {
        clientMacs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        ipGroupId?: pulumi.Input<string | undefined>;
        ips?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        mac?: pulumi.Input<string | undefined>;
        macs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        matchMac?: pulumi.Input<boolean | undefined>;
        matchOppositeIps?: pulumi.Input<boolean | undefined>;
        matchOppositeNetworks?: pulumi.Input<boolean | undefined>;
        matchOppositePorts?: pulumi.Input<boolean | undefined>;
        /**
         * What the source matches: ANY | CLIENT | NETWORK | IP | MAC.
         */
        matchingTarget?: pulumi.Input<string | undefined>;
        /**
         * Refines the source match: OBJECT (saved group) | SPECIFIC (inline values).
         */
        matchingTargetType?: pulumi.Input<string | undefined>;
        networkIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        port?: pulumi.Input<string | undefined>;
        portGroupId?: pulumi.Input<string | undefined>;
        portMatchingType?: pulumi.Input<string | undefined>;
        zoneId: pulumi.Input<string>;
    }

    export interface NetworkIgmpQuerierSwitchArgs {
        querierAddress: pulumi.Input<string>;
        switchMac: pulumi.Input<string>;
    }

    export interface NetworkNatOutboundIpArgs {
        ipAddress?: pulumi.Input<string | undefined>;
        ipAddressPool?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        /**
         * Outbound NAT strategy: all | ip_address | ip_address_pool.
         */
        mode?: pulumi.Input<string | undefined>;
        /**
         * WAN interface group the mapping applies to: WAN | WAN2.
         */
        wanNetworkGroup?: pulumi.Input<string | undefined>;
    }

    export interface NetworkWanDhcpOptionArgs {
        optionNumber: pulumi.Input<number>;
        value: pulumi.Input<string>;
    }

    export interface NetworkWanProviderCapabilitiesArgs {
        downloadKilobitsPerSecond?: pulumi.Input<number | undefined>;
        uploadKilobitsPerSecond?: pulumi.Input<number | undefined>;
    }

    export interface PortForwardDestinationIpArgs {
        destinationIp?: pulumi.Input<string | undefined>;
        /**
         * WAN interface this destination IP binds to: wan | wan2.
         */
        interface?: pulumi.Input<string | undefined>;
    }

    export interface PortProfileDot1xArgs {
        ctrl?: pulumi.Input<string | undefined>;
        idleTimeout?: pulumi.Input<number | undefined>;
    }

    export interface PortProfileEgressRateLimitArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        kbps?: pulumi.Input<number | undefined>;
    }

    export interface PortProfileLinkArgs {
        autoneg?: pulumi.Input<boolean | undefined>;
        fecMode?: pulumi.Input<string | undefined>;
        fullDuplex?: pulumi.Input<boolean | undefined>;
        speed?: pulumi.Input<number | undefined>;
    }

    export interface PortProfileLldpMedArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        notifyEnabled?: pulumi.Input<boolean | undefined>;
    }

    export interface PortProfilePortSecurityArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        macAddresses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    }

    export interface PortProfilePriorityQueuesArgs {
        queue1Level?: pulumi.Input<number | undefined>;
        queue2Level?: pulumi.Input<number | undefined>;
        queue3Level?: pulumi.Input<number | undefined>;
        queue4Level?: pulumi.Input<number | undefined>;
    }

    export interface PortProfileStormControlArgs {
        broadcastEnabled?: pulumi.Input<boolean | undefined>;
        broadcastLevel?: pulumi.Input<number | undefined>;
        broadcastRate?: pulumi.Input<number | undefined>;
        multicastEnabled?: pulumi.Input<boolean | undefined>;
        multicastLevel?: pulumi.Input<number | undefined>;
        multicastRate?: pulumi.Input<number | undefined>;
        type?: pulumi.Input<string | undefined>;
        unknownUnicastEnabled?: pulumi.Input<boolean | undefined>;
        unknownUnicastLevel?: pulumi.Input<number | undefined>;
        unknownUnicastRate?: pulumi.Input<number | undefined>;
    }

    export interface PortProfileVlanArgs {
        excludedNetworkIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        forward?: pulumi.Input<string | undefined>;
        multicastRouterNetworkIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        nativeNetworkId?: pulumi.Input<string | undefined>;
        taggedVlanMgmt?: pulumi.Input<string | undefined>;
        voiceNetworkId?: pulumi.Input<string | undefined>;
    }

    export interface VlanDhcpArgs {
        bootEnabled?: pulumi.Input<boolean | undefined>;
        bootFilename?: pulumi.Input<string | undefined>;
        bootServer?: pulumi.Input<string | undefined>;
        conflictChecking?: pulumi.Input<boolean | undefined>;
        dns1?: pulumi.Input<string | undefined>;
        dns2?: pulumi.Input<string | undefined>;
        dns3?: pulumi.Input<string | undefined>;
        dns4?: pulumi.Input<string | undefined>;
        dnsEnabled?: pulumi.Input<boolean | undefined>;
        enabled?: pulumi.Input<boolean | undefined>;
        gateway?: pulumi.Input<string | undefined>;
        gatewayEnabled?: pulumi.Input<boolean | undefined>;
        guardEnabled?: pulumi.Input<boolean | undefined>;
        lease?: pulumi.Input<number | undefined>;
        ntp1?: pulumi.Input<string | undefined>;
        ntp2?: pulumi.Input<string | undefined>;
        ntpEnabled?: pulumi.Input<boolean | undefined>;
        relayEnabled?: pulumi.Input<boolean | undefined>;
        start?: pulumi.Input<string | undefined>;
        stop?: pulumi.Input<string | undefined>;
        tftpServer?: pulumi.Input<string | undefined>;
        timeOffset?: pulumi.Input<number | undefined>;
        timeOffsetEnabled?: pulumi.Input<boolean | undefined>;
        unifiController?: pulumi.Input<string | undefined>;
        wins1?: pulumi.Input<string | undefined>;
        wins2?: pulumi.Input<string | undefined>;
        winsEnabled?: pulumi.Input<boolean | undefined>;
        wpadUrl?: pulumi.Input<string | undefined>;
    }

    export interface VlanDhcpV6Args {
        allowSlaac?: pulumi.Input<boolean | undefined>;
        dns1?: pulumi.Input<string | undefined>;
        dns2?: pulumi.Input<string | undefined>;
        dns3?: pulumi.Input<string | undefined>;
        dns4?: pulumi.Input<string | undefined>;
        dnsAuto?: pulumi.Input<boolean | undefined>;
        enabled?: pulumi.Input<boolean | undefined>;
        lease?: pulumi.Input<number | undefined>;
        start?: pulumi.Input<string | undefined>;
        stop?: pulumi.Input<string | undefined>;
    }

    export interface VlanIgmpArgs {
        fastLeave?: pulumi.Input<boolean | undefined>;
        forwardUnknownMulticast?: pulumi.Input<boolean | undefined>;
        groupMembership?: pulumi.Input<number | undefined>;
        maxResponse?: pulumi.Input<number | undefined>;
        mcrtrExpireTime?: pulumi.Input<number | undefined>;
        proxyDownstreamNetworkIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        proxyFor?: pulumi.Input<string | undefined>;
        proxyUpstream?: pulumi.Input<boolean | undefined>;
        querierSwitches?: pulumi.Input<pulumi.Input<inputs.network.NetworkIgmpQuerierSwitchArgs>[] | undefined>;
        snooping?: pulumi.Input<boolean | undefined>;
        suppression?: pulumi.Input<boolean | undefined>;
    }

    export interface VlanIpv6Args {
        clientAddressAssignment?: pulumi.Input<string | undefined>;
        interfaceType?: pulumi.Input<string | undefined>;
        pdAutoPrefixIdEnabled?: pulumi.Input<boolean | undefined>;
        pdInterface?: pulumi.Input<string | undefined>;
        pdPrefixId?: pulumi.Input<string | undefined>;
        pdStart?: pulumi.Input<string | undefined>;
        pdStop?: pulumi.Input<string | undefined>;
        raEnabled?: pulumi.Input<boolean | undefined>;
        raPreferredLifetime?: pulumi.Input<number | undefined>;
        raPriority?: pulumi.Input<string | undefined>;
        raValidLifetime?: pulumi.Input<number | undefined>;
        settingPreference?: pulumi.Input<string | undefined>;
        singleNetworkInterface?: pulumi.Input<string | undefined>;
        subnet?: pulumi.Input<string | undefined>;
        wanDelegationType?: pulumi.Input<string | undefined>;
    }

    export interface VlanNatArgs {
        masquerade?: pulumi.Input<boolean | undefined>;
        outboundIpAddresses?: pulumi.Input<pulumi.Input<inputs.network.NetworkNatOutboundIpArgs>[] | undefined>;
    }

    export interface VlanWanArgs {
        dhcpCos?: pulumi.Input<number | undefined>;
        dhcpOptions?: pulumi.Input<pulumi.Input<inputs.network.NetworkWanDhcpOptionArgs>[] | undefined>;
        dhcpv6PdSize?: pulumi.Input<number | undefined>;
        dns1?: pulumi.Input<string | undefined>;
        dns2?: pulumi.Input<string | undefined>;
        dns3?: pulumi.Input<string | undefined>;
        dns4?: pulumi.Input<string | undefined>;
        dnsPreference?: pulumi.Input<string | undefined>;
        dsliteRemoteHost?: pulumi.Input<string | undefined>;
        egressQos?: pulumi.Input<number | undefined>;
        gateway?: pulumi.Input<string | undefined>;
        gatewayV6?: pulumi.Input<string | undefined>;
        ip?: pulumi.Input<string | undefined>;
        ipAliases?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        ipv6?: pulumi.Input<string | undefined>;
        ipv6Dns1?: pulumi.Input<string | undefined>;
        ipv6Dns2?: pulumi.Input<string | undefined>;
        ipv6DnsPreference?: pulumi.Input<string | undefined>;
        loadBalanceType?: pulumi.Input<string | undefined>;
        loadBalanceWeight?: pulumi.Input<number | undefined>;
        netmask?: pulumi.Input<string | undefined>;
        networkGroup?: pulumi.Input<string | undefined>;
        password?: pulumi.Input<string | undefined>;
        pppoePasswordEnabled?: pulumi.Input<boolean | undefined>;
        pppoeUsernameEnabled?: pulumi.Input<boolean | undefined>;
        prefixlen?: pulumi.Input<number | undefined>;
        providerCapabilities?: pulumi.Input<inputs.network.NetworkWanProviderCapabilitiesArgs | undefined>;
        smartqDownRate?: pulumi.Input<number | undefined>;
        smartqEnabled?: pulumi.Input<boolean | undefined>;
        smartqUpRate?: pulumi.Input<number | undefined>;
        type?: pulumi.Input<string | undefined>;
        typeV6?: pulumi.Input<string | undefined>;
        username?: pulumi.Input<string | undefined>;
        vlan?: pulumi.Input<number | undefined>;
        vlanEnabled?: pulumi.Input<boolean | undefined>;
    }

    export interface WlanApGroupsArgs {
        ids?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        mode?: pulumi.Input<string | undefined>;
    }

    export interface WlanBandSteeringArgs {
        band?: pulumi.Input<string | undefined>;
        bands?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        no2GhzOui?: pulumi.Input<boolean | undefined>;
    }

    export interface WlanDpiArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        groupId?: pulumi.Input<string | undefined>;
    }

    export interface WlanDtimArgs {
        mode?: pulumi.Input<string | undefined>;
        na?: pulumi.Input<number | undefined>;
        ng?: pulumi.Input<number | undefined>;
        sixE?: pulumi.Input<number | undefined>;
    }

    export interface WlanIotArgs {
        enhanced?: pulumi.Input<boolean | undefined>;
        optimizeWifiConnectivity?: pulumi.Input<boolean | undefined>;
    }

    export interface WlanMacFilterArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        list?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        policy?: pulumi.Input<string | undefined>;
    }

    export interface WlanMinrateArgs {
        naAdvertisingRates?: pulumi.Input<boolean | undefined>;
        naDataRateKbps?: pulumi.Input<number | undefined>;
        naEnabled?: pulumi.Input<boolean | undefined>;
        ngAdvertisingRates?: pulumi.Input<boolean | undefined>;
        ngDataRateKbps?: pulumi.Input<number | undefined>;
        ngEnabled?: pulumi.Input<boolean | undefined>;
        settingPreference?: pulumi.Input<string | undefined>;
    }

    export interface WlanMulticastArgs {
        broadcastFilterEnabled?: pulumi.Input<boolean | undefined>;
        broadcastFilterList?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        enhanceEnabled?: pulumi.Input<boolean | undefined>;
        proxyArp?: pulumi.Input<boolean | undefined>;
    }

    export interface WlanP2pArgs {
        crossConnect?: pulumi.Input<boolean | undefined>;
        enabled?: pulumi.Input<boolean | undefined>;
    }

    export interface WlanPrivatePresharedKeysArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        keys?: pulumi.Input<pulumi.Input<inputs.network.WlanPrivatePskArgs>[] | undefined>;
    }

    export interface WlanPrivatePskArgs {
        networkId?: pulumi.Input<string | undefined>;
        password: pulumi.Input<string>;
    }

    export interface WlanRadiusArgs {
        dasEnabled?: pulumi.Input<boolean | undefined>;
        macAuthEnabled?: pulumi.Input<boolean | undefined>;
        macaclEmptyPassword?: pulumi.Input<boolean | undefined>;
        macaclFormat?: pulumi.Input<string | undefined>;
        nasIdentifier?: pulumi.Input<string | undefined>;
        nasIdentifierType?: pulumi.Input<string | undefined>;
        profileId?: pulumi.Input<string | undefined>;
    }

    export interface WlanRoamingArgs {
        bssTransition?: pulumi.Input<boolean | undefined>;
        fastRoamingEnabled?: pulumi.Input<boolean | undefined>;
        iappKey?: pulumi.Input<string | undefined>;
    }

    export interface WlanSaeArgs {
        antiClogging?: pulumi.Input<number | undefined>;
        groups?: pulumi.Input<pulumi.Input<number>[] | undefined>;
        psks?: pulumi.Input<pulumi.Input<inputs.network.WlanSaePskArgs>[] | undefined>;
        sync?: pulumi.Input<number | undefined>;
    }

    export interface WlanSaePskArgs {
        id?: pulumi.Input<string | undefined>;
        mac?: pulumi.Input<string | undefined>;
        psk: pulumi.Input<string>;
        vlan?: pulumi.Input<number | undefined>;
    }

    export interface WlanScheduleArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        entries?: pulumi.Input<pulumi.Input<inputs.network.WlanScheduleEntryArgs>[] | undefined>;
        legacy?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    }

    export interface WlanScheduleEntryArgs {
        durationMinutes: pulumi.Input<number>;
        name?: pulumi.Input<string | undefined>;
        startDaysOfWeek?: pulumi.Input<pulumi.Input<string>[] | undefined>;
        startHour: pulumi.Input<number>;
        startMinute?: pulumi.Input<number | undefined>;
    }

    export interface WlanVlanTaggingArgs {
        enabled?: pulumi.Input<boolean | undefined>;
        vlan?: pulumi.Input<number | undefined>;
    }

    export interface WlanWepArgs {
        index?: pulumi.Input<number | undefined>;
        key?: pulumi.Input<string | undefined>;
    }

    export interface WlanWpaArgs {
        enc?: pulumi.Input<string | undefined>;
        groupRekey?: pulumi.Input<number | undefined>;
        mode?: pulumi.Input<string | undefined>;
        pmfCipher?: pulumi.Input<string | undefined>;
        pmfMode?: pulumi.Input<string | undefined>;
        pskRadius?: pulumi.Input<string | undefined>;
    }

    export interface WlanWpa3Args {
        enhanced192?: pulumi.Input<boolean | undefined>;
        fastRoaming?: pulumi.Input<boolean | undefined>;
        support?: pulumi.Input<boolean | undefined>;
        transition?: pulumi.Input<boolean | undefined>;
    }
}

export namespace protect {
    export interface AlarmConditionArgs {
        source: pulumi.Input<string>;
        type?: pulumi.Input<string | undefined>;
        value?: pulumi.Input<string | undefined>;
    }

    export interface AlarmCooldownArgs {
        enabled: pulumi.Input<boolean>;
        timeoutMs: pulumi.Input<number>;
    }

    export interface AlarmSourceArgs {
        device: pulumi.Input<string>;
        type?: pulumi.Input<string | undefined>;
    }

    export interface AlarmWebhookActionArgs {
        headers?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
        method?: pulumi.Input<string | undefined>;
        timeoutMs?: pulumi.Input<number | undefined>;
        url: pulumi.Input<string>;
        useThumbnail?: pulumi.Input<boolean | undefined>;
    }
}
