// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace network {
    export interface DeviceDot1x {
        fallbackNetworkId?: string;
        portControlEnabled?: boolean;
    }

    export interface DeviceEtherLightingArgs {
        behavior?: string;
        brightness?: number;
        ledMode?: string;
        mode?: string;
    }

    export interface DeviceEthernetOverride {
        ifname: string;
        networkGroup?: string;
    }

    export interface DeviceLcm {
        brightness?: number;
        idleTimeout?: number;
        nightModeBegins?: string;
        nightModeEnds?: string;
        orientationOverride?: number;
    }

    export interface DeviceLed {
        etherLighting?: outputs.network.DeviceEtherLightingArgs;
        override?: string;
        overrideColor?: string;
        overrideColorBrightness?: number;
    }

    export interface DeviceOutlet {
        enabled?: boolean;
        overrides?: outputs.network.DeviceOutletOverride[];
        powerCycleEnabled?: boolean;
    }

    export interface DeviceOutletOverride {
        cycleEnabled?: boolean;
        index: number;
        name?: string;
        relayState?: boolean;
    }

    export interface DevicePortOverride {
        aggregateNumPorts?: number;
        autoneg?: boolean;
        dot1xCtrl?: string;
        dot1xIdleTimeout?: number;
        egressRateLimitKbps?: number;
        egressRateLimitKbpsEnabled?: boolean;
        excludedNetworkIds?: string[];
        fecMode?: string;
        forward?: string;
        fullDuplex?: boolean;
        isolation?: boolean;
        lldpmedEnabled?: boolean;
        lldpmedNotifyEnabled?: boolean;
        mirrorPortIdx?: number;
        name?: string;
        nativeNetworkId?: string;
        opMode?: string;
        poeMode?: string;
        portIdx: number;
        portKeepaliveEnabled?: boolean;
        portProfileId?: string;
        portSecurityEnabled?: boolean;
        portSecurityMacAddress?: string[];
        priorityQueue1Level?: number;
        priorityQueue2Level?: number;
        priorityQueue3Level?: number;
        priorityQueue4Level?: number;
        settingPreference?: string;
        speed?: number;
        stormctrlBroadcastEnabled?: boolean;
        stormctrlBroadcastLevel?: number;
        stormctrlBroadcastRate?: number;
        stormctrlMcastEnabled?: boolean;
        stormctrlMcastLevel?: number;
        stormctrlMcastRate?: number;
        stormctrlType?: string;
        stormctrlUcastEnabled?: boolean;
        stormctrlUcastLevel?: number;
        stormctrlUcastRate?: number;
        stpPortMode?: boolean;
        taggedVlanMgmt?: string;
        voiceNetworkId?: string;
    }

    export interface DeviceRadioOverride {
        antennaGain?: number;
        channel?: string;
        channelWidth?: number;
        minRssi?: number;
        minRssiEnabled?: boolean;
        name?: string;
        radio: string;
        txPower?: string;
        txPowerMode?: string;
    }

    export interface DeviceSnmp {
        contact?: string;
        location?: string;
    }

    export interface DeviceStp {
        priority?: string;
        version?: string;
    }

    export interface DeviceSwitching {
        flowControlEnabled?: boolean;
        jumboFrameEnabled?: boolean;
        poeMode?: string;
        vlanEnabled?: boolean;
    }

    export interface DeviceVrrp {
        mode?: string;
        priority?: number;
    }

    export interface FirewallRuleConnectionState {
        established?: boolean;
        invalid?: boolean;
        new?: boolean;
        related?: boolean;
    }

    export interface FirewallRuleDestination {
        address?: string;
        addressIpv6?: string;
        firewallGroupIds?: string[];
        networkId?: string;
        networkType?: string;
        port?: string;
    }

    export interface FirewallRuleProtocolMatch {
        icmpTypename?: string;
        icmpv6Typename?: string;
        matchExcepted?: boolean;
        protocol?: string;
        protocolV6?: string;
    }

    export interface FirewallRuleSource {
        address?: string;
        addressIpv6?: string;
        firewallGroupIds?: string[];
        mac?: string;
        networkId?: string;
        networkType?: string;
        port?: string;
    }

    export interface FirewallZonePolicyDestinationArgs {
        appCategoryIds?: string[];
        appIds?: string[];
        ipGroupId?: string;
        ips?: string[];
        matchOppositeIps?: boolean;
        matchOppositePorts?: boolean;
        /**
         * What the destination matches: ANY | APP | APP_CATEGORY | IP | REGION | WEB.
         */
        matchingTarget?: string;
        /**
         * Refines the destination match: ANY | OBJECT (saved group) | SPECIFIC (inline values).
         */
        matchingTargetType?: string;
        port?: string;
        portGroupId?: string;
        portMatchingType?: string;
        regions?: string[];
        webDomains?: string[];
        zoneId: string;
    }

    export interface FirewallZonePolicyMatchingArgs {
        /**
         * Connection-state matching: ALL | RESPOND_ONLY | CUSTOM.
         */
        connectionStateType?: string;
        connectionStates?: string[];
        /**
         * L3 version the policy matches: BOTH | IPV4 | IPV6.
         */
        ipVersion?: string;
        matchIpSec?: boolean;
        /**
         * IPsec matching mode: MATCH_IP_SEC | MATCH_NON_IP_SEC.
         */
        matchIpSecType?: string;
        matchOppositeProtocol?: boolean;
        protocol?: string;
    }

    export interface FirewallZonePolicyScheduleArgs {
        date?: string;
        dateEnd?: string;
        dateStart?: string;
        /**
         * Schedule pattern: ALWAYS | EVERY_DAY | EVERY_WEEK | ONE_TIME_ONLY | CUSTOM.
         */
        mode?: string;
        repeatOnDays?: string[];
        timeAllDay?: boolean;
        timeRangeEnd?: string;
        timeRangeStart?: string;
    }

    export interface FirewallZonePolicySourceArgs {
        clientMacs?: string[];
        ipGroupId?: string;
        ips?: string[];
        mac?: string;
        macs?: string[];
        matchMac?: boolean;
        matchOppositeIps?: boolean;
        matchOppositeNetworks?: boolean;
        matchOppositePorts?: boolean;
        /**
         * What the source matches: ANY | CLIENT | NETWORK | IP | MAC.
         */
        matchingTarget?: string;
        /**
         * Refines the source match: OBJECT (saved group) | SPECIFIC (inline values).
         */
        matchingTargetType?: string;
        networkIds?: string[];
        port?: string;
        portGroupId?: string;
        portMatchingType?: string;
        zoneId: string;
    }

    export interface NetworkIgmpQuerierSwitch {
        querierAddress: string;
        switchMac: string;
    }

    export interface NetworkNatOutboundIp {
        ipAddress?: string;
        ipAddressPool?: string[];
        /**
         * Outbound NAT strategy: all | ip_address | ip_address_pool.
         */
        mode?: string;
        /**
         * WAN interface group the mapping applies to: WAN | WAN2.
         */
        wanNetworkGroup?: string;
    }

    export interface NetworkWanDhcpOption {
        optionNumber: number;
        value: string;
    }

    export interface NetworkWanProviderCapabilities {
        downloadKilobitsPerSecond?: number;
        uploadKilobitsPerSecond?: number;
    }

    export interface PortForwardDestinationIp {
        destinationIp?: string;
        /**
         * WAN interface this destination IP binds to: wan | wan2.
         */
        interface?: string;
    }

    export interface PortProfileDot1x {
        ctrl?: string;
        idleTimeout?: number;
    }

    export interface PortProfileEgressRateLimit {
        enabled?: boolean;
        kbps?: number;
    }

    export interface PortProfileLink {
        autoneg?: boolean;
        fecMode?: string;
        fullDuplex?: boolean;
        speed?: number;
    }

    export interface PortProfileLldpMed {
        enabled?: boolean;
        notifyEnabled?: boolean;
    }

    export interface PortProfilePortSecurity {
        enabled?: boolean;
        macAddresses?: string[];
    }

    export interface PortProfilePriorityQueues {
        queue1Level?: number;
        queue2Level?: number;
        queue3Level?: number;
        queue4Level?: number;
    }

    export interface PortProfileStormControl {
        broadcastEnabled?: boolean;
        broadcastLevel?: number;
        broadcastRate?: number;
        multicastEnabled?: boolean;
        multicastLevel?: number;
        multicastRate?: number;
        type?: string;
        unknownUnicastEnabled?: boolean;
        unknownUnicastLevel?: number;
        unknownUnicastRate?: number;
    }

    export interface PortProfileVlan {
        excludedNetworkIds?: string[];
        forward?: string;
        multicastRouterNetworkIds?: string[];
        nativeNetworkId?: string;
        taggedVlanMgmt?: string;
        voiceNetworkId?: string;
    }

    export interface VlanDhcp {
        bootEnabled?: boolean;
        bootFilename?: string;
        bootServer?: string;
        conflictChecking?: boolean;
        dns1?: string;
        dns2?: string;
        dns3?: string;
        dns4?: string;
        dnsEnabled?: boolean;
        enabled?: boolean;
        gateway?: string;
        gatewayEnabled?: boolean;
        guardEnabled?: boolean;
        lease?: number;
        ntp1?: string;
        ntp2?: string;
        ntpEnabled?: boolean;
        relayEnabled?: boolean;
        start?: string;
        stop?: string;
        tftpServer?: string;
        timeOffset?: number;
        timeOffsetEnabled?: boolean;
        unifiController?: string;
        wins1?: string;
        wins2?: string;
        winsEnabled?: boolean;
        wpadUrl?: string;
    }

    export interface VlanDhcpV6 {
        allowSlaac?: boolean;
        dns1?: string;
        dns2?: string;
        dns3?: string;
        dns4?: string;
        dnsAuto?: boolean;
        enabled?: boolean;
        lease?: number;
        start?: string;
        stop?: string;
    }

    export interface VlanIgmp {
        fastLeave?: boolean;
        forwardUnknownMulticast?: boolean;
        groupMembership?: number;
        maxResponse?: number;
        mcrtrExpireTime?: number;
        proxyDownstreamNetworkIds?: string[];
        proxyFor?: string;
        proxyUpstream?: boolean;
        querierSwitches?: outputs.network.NetworkIgmpQuerierSwitch[];
        snooping?: boolean;
        suppression?: boolean;
    }

    export interface VlanIpv6 {
        clientAddressAssignment?: string;
        interfaceType?: string;
        pdAutoPrefixIdEnabled?: boolean;
        pdInterface?: string;
        pdPrefixId?: string;
        pdStart?: string;
        pdStop?: string;
        raEnabled?: boolean;
        raPreferredLifetime?: number;
        raPriority?: string;
        raValidLifetime?: number;
        settingPreference?: string;
        singleNetworkInterface?: string;
        subnet?: string;
        wanDelegationType?: string;
    }

    export interface VlanNat {
        masquerade?: boolean;
        outboundIpAddresses?: outputs.network.NetworkNatOutboundIp[];
    }

    export interface VlanWan {
        dhcpCos?: number;
        dhcpOptions?: outputs.network.NetworkWanDhcpOption[];
        dhcpv6PdSize?: number;
        dns1?: string;
        dns2?: string;
        dns3?: string;
        dns4?: string;
        dnsPreference?: string;
        dsliteRemoteHost?: string;
        egressQos?: number;
        gateway?: string;
        gatewayV6?: string;
        ip?: string;
        ipAliases?: string[];
        ipv6?: string;
        ipv6Dns1?: string;
        ipv6Dns2?: string;
        ipv6DnsPreference?: string;
        loadBalanceType?: string;
        loadBalanceWeight?: number;
        netmask?: string;
        networkGroup?: string;
        password?: string;
        pppoePasswordEnabled?: boolean;
        pppoeUsernameEnabled?: boolean;
        prefixlen?: number;
        providerCapabilities?: outputs.network.NetworkWanProviderCapabilities;
        smartqDownRate?: number;
        smartqEnabled?: boolean;
        smartqUpRate?: number;
        type?: string;
        typeV6?: string;
        username?: string;
        vlan?: number;
        vlanEnabled?: boolean;
    }

    export interface WlanApGroups {
        ids?: string[];
        mode?: string;
    }

    export interface WlanBandSteering {
        band?: string;
        bands?: string[];
        no2GhzOui?: boolean;
    }

    export interface WlanDpi {
        enabled?: boolean;
        groupId?: string;
    }

    export interface WlanDtim {
        mode?: string;
        na?: number;
        ng?: number;
        sixE?: number;
    }

    export interface WlanIot {
        enhanced?: boolean;
        optimizeWifiConnectivity?: boolean;
    }

    export interface WlanMacFilter {
        enabled?: boolean;
        list?: string[];
        policy?: string;
    }

    export interface WlanMinrate {
        naAdvertisingRates?: boolean;
        naDataRateKbps?: number;
        naEnabled?: boolean;
        ngAdvertisingRates?: boolean;
        ngDataRateKbps?: number;
        ngEnabled?: boolean;
        settingPreference?: string;
    }

    export interface WlanMulticast {
        broadcastFilterEnabled?: boolean;
        broadcastFilterList?: string[];
        enhanceEnabled?: boolean;
        proxyArp?: boolean;
    }

    export interface WlanP2p {
        crossConnect?: boolean;
        enabled?: boolean;
    }

    export interface WlanPrivatePresharedKeys {
        enabled?: boolean;
        keys?: outputs.network.WlanPrivatePsk[];
    }

    export interface WlanPrivatePsk {
        networkId?: string;
        password: string;
    }

    export interface WlanRadius {
        dasEnabled?: boolean;
        macAuthEnabled?: boolean;
        macaclEmptyPassword?: boolean;
        macaclFormat?: string;
        nasIdentifier?: string;
        nasIdentifierType?: string;
        profileId?: string;
    }

    export interface WlanRoaming {
        bssTransition?: boolean;
        fastRoamingEnabled?: boolean;
        iappKey?: string;
    }

    export interface WlanSae {
        antiClogging?: number;
        groups?: number[];
        psks?: outputs.network.WlanSaePsk[];
        sync?: number;
    }

    export interface WlanSaePsk {
        id?: string;
        mac?: string;
        psk: string;
        vlan?: number;
    }

    export interface WlanSchedule {
        enabled?: boolean;
        entries?: outputs.network.WlanScheduleEntry[];
        legacy?: string[];
    }

    export interface WlanScheduleEntry {
        durationMinutes: number;
        name?: string;
        startDaysOfWeek?: string[];
        startHour: number;
        startMinute?: number;
    }

    export interface WlanVlanTagging {
        enabled?: boolean;
        vlan?: number;
    }

    export interface WlanWep {
        index?: number;
        key?: string;
    }

    export interface WlanWpa {
        enc?: string;
        groupRekey?: number;
        mode?: string;
        pmfCipher?: string;
        pmfMode?: string;
        pskRadius?: string;
    }

    export interface WlanWpa3 {
        enhanced192?: boolean;
        fastRoaming?: boolean;
        support?: boolean;
        transition?: boolean;
    }

}

export namespace protect {
    export interface AlarmCondition {
        source: string;
        type?: string;
        value?: string;
    }

    export interface AlarmCooldown {
        enabled: boolean;
        timeoutMs: number;
    }

    export interface AlarmSource {
        device: string;
        type?: string;
    }

    export interface AlarmWebhookAction {
        headers?: {[key: string]: string};
        method?: string;
        timeoutMs?: number;
        url: string;
        useThumbnail?: boolean;
    }

}
