// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * A UniFi Protect Alarm Manager rule (sources + conditions -> webhook actions). Uses Protect's private automations API: requires the console's Alarm Manager to be in LOCAL mode, and may require username/password auth. The resource owns the rule's entire actions list.
 */
export class AlarmAutomation extends pulumi.CustomResource {
    /**
     * Get an existing AlarmAutomation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): AlarmAutomation {
        return new AlarmAutomation(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:protect:AlarmAutomation';

    /**
     * Returns true if the given object is an instance of AlarmAutomation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlarmAutomation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlarmAutomation.__pulumiType;
    }

    /**
     * AutomationId is the controller-assigned rule identifier.
     */
    declare public /*out*/ readonly automationId: pulumi.Output<string>;
    /**
     * Conditions are the trigger conditions (ANDed). At least one is required.
     */
    declare public readonly conditions: pulumi.Output<outputs.protect.AlarmCondition[]>;
    /**
     * Cooldown suppresses repeat fires. Defaults to disabled with a 10-minute window.
     */
    declare public readonly cooldown: pulumi.Output<outputs.protect.AlarmCooldown | undefined>;
    /**
     * Enabled controls whether the rule fires. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Name is the rule's display name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Sources scopes the rule to devices. Empty means all devices.
     */
    declare public readonly sources: pulumi.Output<outputs.protect.AlarmSource[] | undefined>;
    /**
     * WebhookActions fire when the rule matches. At least one is required.
     */
    declare public readonly webhookActions: pulumi.Output<outputs.protect.AlarmWebhookAction[]>;

    /**
     * Create a AlarmAutomation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlarmAutomationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.conditions === undefined && !opts.urn) {
                throw new Error("Missing required property 'conditions'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.webhookActions === undefined && !opts.urn) {
                throw new Error("Missing required property 'webhookActions'");
            }
            resourceInputs["conditions"] = args?.conditions;
            resourceInputs["cooldown"] = args?.cooldown;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["name"] = args?.name;
            resourceInputs["sources"] = args?.sources;
            resourceInputs["webhookActions"] = args?.webhookActions;
            resourceInputs["automationId"] = undefined /*out*/;
        } else {
            resourceInputs["automationId"] = undefined /*out*/;
            resourceInputs["conditions"] = undefined /*out*/;
            resourceInputs["cooldown"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["sources"] = undefined /*out*/;
            resourceInputs["webhookActions"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AlarmAutomation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a AlarmAutomation resource.
 */
export interface AlarmAutomationArgs {
    /**
     * Conditions are the trigger conditions (ANDed). At least one is required.
     */
    conditions: pulumi.Input<pulumi.Input<inputs.protect.AlarmConditionArgs>[]>;
    /**
     * Cooldown suppresses repeat fires. Defaults to disabled with a 10-minute window.
     */
    cooldown?: pulumi.Input<inputs.protect.AlarmCooldownArgs | undefined>;
    /**
     * Enabled controls whether the rule fires. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Name is the rule's display name.
     */
    name: pulumi.Input<string>;
    /**
     * Sources scopes the rule to devices. Empty means all devices.
     */
    sources?: pulumi.Input<pulumi.Input<inputs.protect.AlarmSourceArgs>[] | undefined>;
    /**
     * WebhookActions fire when the rule matches. At least one is required.
     */
    webhookActions: pulumi.Input<pulumi.Input<inputs.protect.AlarmWebhookActionArgs>[]>;
}
