// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manage settings of an existing UniFi Protect camera (adoption model; cameras are not created or deleted via the API). Exposes the writable fields of the Protect CameraPatchRequest.
 */
export class Camera extends pulumi.CustomResource {
    /**
     * Get an existing Camera resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Camera {
        return new Camera(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:protect:Camera';

    /**
     * Returns true if the given object is an instance of Camera.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Camera {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Camera.__pulumiType;
    }

    /**
     * CameraId is the Protect camera ID (from the Protect API / bootstrap).
     */
    declare public readonly cameraId: pulumi.Output<string>;
    /**
     * HdrType selects HDR behaviour, e.g. "auto", "always", "off".
     */
    declare public readonly hdrType: pulumi.Output<string | undefined>;
    /**
     * LcdMessageResetAt is the epoch-millisecond timestamp at which the LCD message clears. 0 (or omitted) leaves the message until changed.
     */
    declare public readonly lcdMessageResetAt: pulumi.Output<number | undefined>;
    /**
     * LcdMessageText is the doorbell LCD custom message text (used with type CUSTOM_MESSAGE).
     */
    declare public readonly lcdMessageText: pulumi.Output<string | undefined>;
    /**
     * LcdMessageType is the doorbell LCD message type, e.g. "CUSTOM_MESSAGE", "DO_NOT_DISTURB", "LEAVE_PACKAGE_AT_DOOR" (doorbell cameras only).
     */
    declare public readonly lcdMessageType: pulumi.Output<string | undefined>;
    /**
     * LedEnabled toggles the status LED (ledSettings.isEnabled).
     */
    declare public readonly ledEnabled: pulumi.Output<boolean | undefined>;
    /**
     * MicVolume sets the microphone volume (0-100). A value of 0 is not applied by the Protect API (the field is omitted when zero).
     */
    declare public readonly micVolume: pulumi.Output<number | undefined>;
    /**
     * Name is the camera's display name.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * OsdDateEnabled overlays the date/time on the video (osdSettings.isDateEnabled).
     */
    declare public readonly osdDateEnabled: pulumi.Output<boolean | undefined>;
    /**
     * OsdDebugEnabled overlays debug telemetry on the video (osdSettings.isDebugEnabled).
     */
    declare public readonly osdDebugEnabled: pulumi.Output<boolean | undefined>;
    /**
     * OsdLogoEnabled overlays the logo on the video (osdSettings.isLogoEnabled).
     */
    declare public readonly osdLogoEnabled: pulumi.Output<boolean | undefined>;
    /**
     * OsdNameEnabled overlays the camera name on the video (osdSettings.isNameEnabled).
     */
    declare public readonly osdNameEnabled: pulumi.Output<boolean | undefined>;
    /**
     * SmartDetectAudioTypes selects which sounds trigger smart detections, e.g. "smoke", "cmonitor" (CO alarm), "alrmSmoke", "alrmCmonitor".
     */
    declare public readonly smartDetectAudioTypes: pulumi.Output<string[] | undefined>;
    /**
     * SmartDetectObjectTypes selects which objects trigger smart detections, e.g. "person", "vehicle", "animal", "package", "licensePlate".
     */
    declare public readonly smartDetectObjectTypes: pulumi.Output<string[] | undefined>;
    /**
     * State is the connection state, e.g. "CONNECTED" (read-only).
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * Type is the camera model/type (read-only; the Protect modelKey).
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;
    /**
     * VideoMode selects the capture mode, e.g. "default", "highFps", "sport".
     */
    declare public readonly videoMode: pulumi.Output<string | undefined>;

    /**
     * Create a Camera resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CameraArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.cameraId === undefined && !opts.urn) {
                throw new Error("Missing required property 'cameraId'");
            }
            resourceInputs["cameraId"] = args?.cameraId;
            resourceInputs["hdrType"] = args?.hdrType;
            resourceInputs["lcdMessageResetAt"] = args?.lcdMessageResetAt;
            resourceInputs["lcdMessageText"] = args?.lcdMessageText;
            resourceInputs["lcdMessageType"] = args?.lcdMessageType;
            resourceInputs["ledEnabled"] = args?.ledEnabled;
            resourceInputs["micVolume"] = args?.micVolume;
            resourceInputs["name"] = args?.name;
            resourceInputs["osdDateEnabled"] = args?.osdDateEnabled;
            resourceInputs["osdDebugEnabled"] = args?.osdDebugEnabled;
            resourceInputs["osdLogoEnabled"] = args?.osdLogoEnabled;
            resourceInputs["osdNameEnabled"] = args?.osdNameEnabled;
            resourceInputs["smartDetectAudioTypes"] = args?.smartDetectAudioTypes;
            resourceInputs["smartDetectObjectTypes"] = args?.smartDetectObjectTypes;
            resourceInputs["videoMode"] = args?.videoMode;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        } else {
            resourceInputs["cameraId"] = undefined /*out*/;
            resourceInputs["hdrType"] = undefined /*out*/;
            resourceInputs["lcdMessageResetAt"] = undefined /*out*/;
            resourceInputs["lcdMessageText"] = undefined /*out*/;
            resourceInputs["lcdMessageType"] = undefined /*out*/;
            resourceInputs["ledEnabled"] = undefined /*out*/;
            resourceInputs["micVolume"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["osdDateEnabled"] = undefined /*out*/;
            resourceInputs["osdDebugEnabled"] = undefined /*out*/;
            resourceInputs["osdLogoEnabled"] = undefined /*out*/;
            resourceInputs["osdNameEnabled"] = undefined /*out*/;
            resourceInputs["smartDetectAudioTypes"] = undefined /*out*/;
            resourceInputs["smartDetectObjectTypes"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["videoMode"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["cameraId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Camera.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Camera resource.
 */
export interface CameraArgs {
    /**
     * CameraId is the Protect camera ID (from the Protect API / bootstrap).
     */
    cameraId: pulumi.Input<string>;
    /**
     * HdrType selects HDR behaviour, e.g. "auto", "always", "off".
     */
    hdrType?: pulumi.Input<string | undefined>;
    /**
     * LcdMessageResetAt is the epoch-millisecond timestamp at which the LCD message clears. 0 (or omitted) leaves the message until changed.
     */
    lcdMessageResetAt?: pulumi.Input<number | undefined>;
    /**
     * LcdMessageText is the doorbell LCD custom message text (used with type CUSTOM_MESSAGE).
     */
    lcdMessageText?: pulumi.Input<string | undefined>;
    /**
     * LcdMessageType is the doorbell LCD message type, e.g. "CUSTOM_MESSAGE", "DO_NOT_DISTURB", "LEAVE_PACKAGE_AT_DOOR" (doorbell cameras only).
     */
    lcdMessageType?: pulumi.Input<string | undefined>;
    /**
     * LedEnabled toggles the status LED (ledSettings.isEnabled).
     */
    ledEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * MicVolume sets the microphone volume (0-100). A value of 0 is not applied by the Protect API (the field is omitted when zero).
     */
    micVolume?: pulumi.Input<number | undefined>;
    /**
     * Name is the camera's display name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * OsdDateEnabled overlays the date/time on the video (osdSettings.isDateEnabled).
     */
    osdDateEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * OsdDebugEnabled overlays debug telemetry on the video (osdSettings.isDebugEnabled).
     */
    osdDebugEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * OsdLogoEnabled overlays the logo on the video (osdSettings.isLogoEnabled).
     */
    osdLogoEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * OsdNameEnabled overlays the camera name on the video (osdSettings.isNameEnabled).
     */
    osdNameEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * SmartDetectAudioTypes selects which sounds trigger smart detections, e.g. "smoke", "cmonitor" (CO alarm), "alrmSmoke", "alrmCmonitor".
     */
    smartDetectAudioTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * SmartDetectObjectTypes selects which objects trigger smart detections, e.g. "person", "vehicle", "animal", "package", "licensePlate".
     */
    smartDetectObjectTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * VideoMode selects the capture mode, e.g. "default", "highFps", "sport".
     */
    videoMode?: pulumi.Input<string | undefined>;
}
