// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { CameraArgs } from "./camera";
export type Camera = import("./camera").Camera;
export const Camera: typeof import("./camera").Camera = null as any;
utilities.lazyLoad(exports, ["Camera"], () => require("./camera"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "unifi:protect:Camera":
                return new Camera(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("unifi", "protect", _module)
