// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const NfsPermission = {
    /**
     * Read-write access.
     */
    Rw: "rw",
    /**
     * Read-only access.
     */
    Ro: "ro",
} as const;

export type NfsPermission = (typeof NfsPermission)[keyof typeof NfsPermission];
