// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A UniFi OS integration API key owned by the supplied local user. The full key is returned once and stored as a Pulumi secret.
 */
export class APIKey extends pulumi.CustomResource {
    /**
     * Get an existing APIKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): APIKey {
        return new APIKey(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:os:APIKey';

    /**
     * Returns true if the given object is an instance of APIKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is APIKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === APIKey.__pulumiType;
    }

    /**
     * Full API key. Returned only at creation and stored as a Pulumi secret.
     */
    declare public /*out*/ readonly apiKey: pulumi.Output<string>;
    /**
     * Console-assigned API key identifier.
     */
    declare public /*out*/ readonly keyId: pulumi.Output<string>;
    /**
     * Display name for the integration key.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Password for the local account. Stored as a Pulumi secret.
     */
    declare public readonly password: pulumi.Output<string>;
    /**
     * Local account that owns the key.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a APIKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: APIKeyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["username"] = args?.username;
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["keyId"] = undefined /*out*/;
        } else {
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["keyId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey", "password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["name", "username"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(APIKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a APIKey resource.
 */
export interface APIKeyArgs {
    /**
     * Display name for the integration key.
     */
    name: pulumi.Input<string>;
    /**
     * Password for the local account. Stored as a Pulumi secret.
     */
    password: pulumi.Input<string>;
    /**
     * Local account that will own the key.
     */
    username: pulumi.Input<string>;
}
