// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A custom UniFi OS console role, managed through the private Users API.
 */
export class CustomRole extends pulumi.CustomResource {
    /**
     * Get an existing CustomRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CustomRole {
        return new CustomRole(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:os:CustomRole';

    /**
     * Returns true if the given object is an instance of CustomRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomRole.__pulumiType;
    }

    /**
     * Access access: "admin" or "none".
     */
    declare public readonly accessRole: pulumi.Output<string | undefined>;
    /**
     * Role name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Network access: "admin", "hotspot", "view", "site_admin", or "none".
     */
    declare public readonly networkRole: pulumi.Output<string | undefined>;
    /**
     * Protect access: "admin", "live", "view", or "none".
     */
    declare public readonly protectRole: pulumi.Output<string | undefined>;
    /**
     * Console-assigned role identifier.
     */
    declare public /*out*/ readonly roleId: pulumi.Output<string>;
    /**
     * Talk access: "admin", "view", or "none".
     */
    declare public readonly talkRole: pulumi.Output<string | undefined>;

    /**
     * Create a CustomRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomRoleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["accessRole"] = (args?.accessRole) ?? "none";
            resourceInputs["name"] = args?.name;
            resourceInputs["networkRole"] = (args?.networkRole) ?? "none";
            resourceInputs["protectRole"] = (args?.protectRole) ?? "none";
            resourceInputs["talkRole"] = (args?.talkRole) ?? "none";
            resourceInputs["roleId"] = undefined /*out*/;
        } else {
            resourceInputs["accessRole"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkRole"] = undefined /*out*/;
            resourceInputs["protectRole"] = undefined /*out*/;
            resourceInputs["roleId"] = undefined /*out*/;
            resourceInputs["talkRole"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomRole.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CustomRole resource.
 */
export interface CustomRoleArgs {
    /**
     * Access access: "admin" or "none".
     */
    accessRole?: pulumi.Input<string | undefined>;
    /**
     * Role name.
     */
    name: pulumi.Input<string>;
    /**
     * Network access: "admin", "hotspot", "view", "site_admin", or "none".
     */
    networkRole?: pulumi.Input<string | undefined>;
    /**
     * Protect access: "admin", "live", "view", or "none".
     */
    protectRole?: pulumi.Input<string | undefined>;
    /**
     * Talk access: "admin", "view", or "none".
     */
    talkRole?: pulumi.Input<string | undefined>;
}
