// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A local-only UniFi OS console administrator, managed through the private Users API.
 */
export class LocalAdmin extends pulumi.CustomResource {
    /**
     * Get an existing LocalAdmin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): LocalAdmin {
        return new LocalAdmin(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:os:LocalAdmin';

    /**
     * Returns true if the given object is an instance of LocalAdmin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LocalAdmin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LocalAdmin.__pulumiType;
    }

    /**
     * Local account email label; it need not be deliverable.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * First name.
     */
    declare public readonly firstName: pulumi.Output<string>;
    /**
     * Last name.
     */
    declare public readonly lastName: pulumi.Output<string>;
    /**
     * Local login password. Stored as a Pulumi secret.
     */
    declare public readonly password: pulumi.Output<string>;
    /**
     * UniFi OS role ID.
     */
    declare public readonly roleId: pulumi.Output<string>;
    /**
     * Console-assigned user identifier.
     */
    declare public /*out*/ readonly userId: pulumi.Output<string>;
    /**
     * Local login username. Changing it replaces the user.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a LocalAdmin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LocalAdminArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.firstName === undefined && !opts.urn) {
                throw new Error("Missing required property 'firstName'");
            }
            if (args?.lastName === undefined && !opts.urn) {
                throw new Error("Missing required property 'lastName'");
            }
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.roleId === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleId'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["firstName"] = args?.firstName;
            resourceInputs["lastName"] = args?.lastName;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["roleId"] = args?.roleId;
            resourceInputs["username"] = args?.username;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["firstName"] = undefined /*out*/;
            resourceInputs["lastName"] = undefined /*out*/;
            resourceInputs["password"] = undefined /*out*/;
            resourceInputs["roleId"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["email", "firstName", "lastName", "roleId", "username"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(LocalAdmin.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a LocalAdmin resource.
 */
export interface LocalAdminArgs {
    /**
     * Local account email label; it need not be deliverable.
     */
    email: pulumi.Input<string>;
    /**
     * First name.
     */
    firstName: pulumi.Input<string>;
    /**
     * Last name.
     */
    lastName: pulumi.Input<string>;
    /**
     * Local login password. Stored as a Pulumi secret.
     */
    password: pulumi.Input<string>;
    /**
     * UniFi OS role ID.
     */
    roleId: pulumi.Input<string>;
    /**
     * Local login username. Changing it replaces the user.
     */
    username: pulumi.Input<string>;
}
