// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { NfsExportArgs } from "./nfsExport";
export type NfsExport = import("./nfsExport").NfsExport;
export const NfsExport: typeof import("./nfsExport").NfsExport = null as any;
utilities.lazyLoad(exports, ["NfsExport"], () => require("./nfsExport"));

export { ShareArgs } from "./share";
export type Share = import("./share").Share;
export const Share: typeof import("./share").Share = null as any;
utilities.lazyLoad(exports, ["Share"], () => require("./share"));


// Export enums:
export * from "../types/enums/drive";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "unifi:drive:NfsExport":
                return new NfsExport(name, <any>undefined, { urn })
            case "unifi:drive:Share":
                return new Share(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("unifi", "drive", _module)
