// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

/**
 * An NFS export grant giving one client access to a UniFi Drive shared drive. Owns a single (share, client) entry in the appliance's global NFS export list; writes are read-modify-writes serialised within the provider process. Requires the global NFS service to be enabled on the appliance.
 */
export class NfsExport extends pulumi.CustomResource {
    /**
     * Get an existing NfsExport resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): NfsExport {
        return new NfsExport(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:drive:NfsExport';

    /**
     * Returns true if the given object is an instance of NfsExport.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NfsExport {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NfsExport.__pulumiType;
    }

    /**
     * Client is the NFS client IP or CIDR allowed to mount the drive.
     */
    declare public readonly client: pulumi.Output<string>;
    /**
     * Permission is the access level: "rw" (default) or "ro".
     */
    declare public readonly permission: pulumi.Output<enums.drive.NfsPermission | undefined>;
    /**
     * ShareId is the drive to export (the shareId of a unifi:drive:Share).
     */
    declare public readonly shareId: pulumi.Output<string>;
    /**
     * ShareName is the exported drive's name (resolved from ShareId).
     */
    declare public /*out*/ readonly shareName: pulumi.Output<string>;

    /**
     * Create a NfsExport resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NfsExportArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.client === undefined && !opts.urn) {
                throw new Error("Missing required property 'client'");
            }
            if (args?.shareId === undefined && !opts.urn) {
                throw new Error("Missing required property 'shareId'");
            }
            resourceInputs["client"] = args?.client;
            resourceInputs["permission"] = (args?.permission) ?? "rw";
            resourceInputs["shareId"] = args?.shareId;
            resourceInputs["shareName"] = undefined /*out*/;
        } else {
            resourceInputs["client"] = undefined /*out*/;
            resourceInputs["permission"] = undefined /*out*/;
            resourceInputs["shareId"] = undefined /*out*/;
            resourceInputs["shareName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["client", "shareId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(NfsExport.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a NfsExport resource.
 */
export interface NfsExportArgs {
    /**
     * Client is the NFS client IP or CIDR allowed to mount the drive.
     */
    client: pulumi.Input<string>;
    /**
     * Permission is the access level: "rw" (default) or "ro".
     */
    permission?: pulumi.Input<enums.drive.NfsPermission | undefined>;
    /**
     * ShareId is the drive to export (the shareId of a unifi:drive:Share).
     */
    shareId: pulumi.Input<string>;
}
