// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A UniFi Drive shared drive on a UNAS appliance. Managed via UniFi Drive's PRIVATE /proxy/drive API (the UNAS is a separate host — configure `unasUrl`/`unasUsername`/`unasPassword`). The API supports only create and delete, so every input is replace-only: changing name, pool, or quota REPLACES the drive and DELETES its data. Use `pulumi.protect(true)` to guard important drives.
 */
export class Share extends pulumi.CustomResource {
    /**
     * Get an existing Share resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Share {
        return new Share(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:drive:Share';

    /**
     * Returns true if the given object is an instance of Share.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Share {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Share.__pulumiType;
    }

    /**
     * ExportPath is the documented NFS export path for the drive, e.g. /var/nfs/shared/<name>.
     */
    declare public /*out*/ readonly exportPath: pulumi.Output<string>;
    /**
     * Name is the shared drive's name. Must be unique on the appliance. Changing it replaces (and deletes) the drive.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * PoolId is the storage pool the drive actually lives in (resolved when StoragePoolId is omitted).
     */
    declare public /*out*/ readonly poolId: pulumi.Output<string>;
    /**
     * QuotaGib is the size limit in gibibytes. Omit (or <= 0) for no quota.
     */
    declare public readonly quotaGib: pulumi.Output<number | undefined>;
    /**
     * ShareId is the appliance-assigned drive identifier.
     */
    declare public /*out*/ readonly shareId: pulumi.Output<string>;
    /**
     * StoragePoolId pins the storage pool. Omit to use the appliance's first pool.
     */
    declare public readonly storagePoolId: pulumi.Output<string | undefined>;

    /**
     * Create a Share resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ShareArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["quotaGib"] = args?.quotaGib;
            resourceInputs["storagePoolId"] = args?.storagePoolId;
            resourceInputs["exportPath"] = undefined /*out*/;
            resourceInputs["poolId"] = undefined /*out*/;
            resourceInputs["shareId"] = undefined /*out*/;
        } else {
            resourceInputs["exportPath"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["poolId"] = undefined /*out*/;
            resourceInputs["quotaGib"] = undefined /*out*/;
            resourceInputs["shareId"] = undefined /*out*/;
            resourceInputs["storagePoolId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["name", "quotaGib", "storagePoolId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Share.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Share resource.
 */
export interface ShareArgs {
    /**
     * Name is the shared drive's name. Must be unique on the appliance. Changing it replaces (and deletes) the drive.
     */
    name: pulumi.Input<string>;
    /**
     * QuotaGib is the size limit in gibibytes. Omit (or <= 0) for no quota.
     */
    quotaGib?: pulumi.Input<number | undefined>;
    /**
     * StoragePoolId pins the storage pool. Omit to use the appliance's first pool.
     */
    storagePoolId?: pulumi.Input<string | undefined>;
}
