// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Manage settings of an existing, already-adopted UniFi network device (gateway, switch, access point, PDU). Adoption model: binds to a device by MAC and read-modify-writes only the managed fields onto the controller's current device object; unmanaged settings and unlisted port/outlet/radio overrides are preserved. Delete is a no-op.
 */
export class Device extends pulumi.CustomResource {
    /**
     * Get an existing Device resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Device {
        return new Device(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:Device';

    /**
     * Returns true if the given object is an instance of Device.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Device {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Device.__pulumiType;
    }

    declare public /*out*/ readonly adopted: pulumi.Output<boolean>;
    declare public /*out*/ readonly deviceId: pulumi.Output<string>;
    declare public readonly disabled: pulumi.Output<boolean | undefined>;
    declare public readonly dot1x: pulumi.Output<outputs.network.DeviceDot1x | undefined>;
    declare public readonly ethernetOverrides: pulumi.Output<outputs.network.DeviceEthernetOverride[] | undefined>;
    declare public readonly lcm: pulumi.Output<outputs.network.DeviceLcm | undefined>;
    declare public readonly led: pulumi.Output<outputs.network.DeviceLed | undefined>;
    declare public readonly mac: pulumi.Output<string>;
    declare public readonly mgmtNetworkId: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly model: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string | undefined>;
    declare public readonly outlet: pulumi.Output<outputs.network.DeviceOutlet | undefined>;
    declare public readonly portOverrides: pulumi.Output<outputs.network.DevicePortOverride[] | undefined>;
    declare public readonly radioTable: pulumi.Output<outputs.network.DeviceRadioOverride[] | undefined>;
    declare public readonly snmp: pulumi.Output<outputs.network.DeviceSnmp | undefined>;
    declare public /*out*/ readonly state: pulumi.Output<string>;
    declare public readonly stp: pulumi.Output<outputs.network.DeviceStp | undefined>;
    declare public readonly switching: pulumi.Output<outputs.network.DeviceSwitching | undefined>;
    declare public /*out*/ readonly type: pulumi.Output<string>;
    declare public readonly vrrp: pulumi.Output<outputs.network.DeviceVrrp | undefined>;

    /**
     * Create a Device resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DeviceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.mac === undefined && !opts.urn) {
                throw new Error("Missing required property 'mac'");
            }
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["dot1x"] = args?.dot1x;
            resourceInputs["ethernetOverrides"] = args?.ethernetOverrides;
            resourceInputs["lcm"] = args?.lcm;
            resourceInputs["led"] = args?.led;
            resourceInputs["mac"] = args?.mac;
            resourceInputs["mgmtNetworkId"] = args?.mgmtNetworkId;
            resourceInputs["name"] = args?.name;
            resourceInputs["outlet"] = args?.outlet;
            resourceInputs["portOverrides"] = args?.portOverrides;
            resourceInputs["radioTable"] = args?.radioTable;
            resourceInputs["snmp"] = args?.snmp;
            resourceInputs["stp"] = args?.stp;
            resourceInputs["switching"] = args?.switching;
            resourceInputs["vrrp"] = args?.vrrp;
            resourceInputs["adopted"] = undefined /*out*/;
            resourceInputs["deviceId"] = undefined /*out*/;
            resourceInputs["model"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        } else {
            resourceInputs["adopted"] = undefined /*out*/;
            resourceInputs["deviceId"] = undefined /*out*/;
            resourceInputs["disabled"] = undefined /*out*/;
            resourceInputs["dot1x"] = undefined /*out*/;
            resourceInputs["ethernetOverrides"] = undefined /*out*/;
            resourceInputs["lcm"] = undefined /*out*/;
            resourceInputs["led"] = undefined /*out*/;
            resourceInputs["mac"] = undefined /*out*/;
            resourceInputs["mgmtNetworkId"] = undefined /*out*/;
            resourceInputs["model"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["outlet"] = undefined /*out*/;
            resourceInputs["portOverrides"] = undefined /*out*/;
            resourceInputs["radioTable"] = undefined /*out*/;
            resourceInputs["snmp"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["stp"] = undefined /*out*/;
            resourceInputs["switching"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["vrrp"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Device.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Device resource.
 */
export interface DeviceArgs {
    disabled?: pulumi.Input<boolean | undefined>;
    dot1x?: pulumi.Input<inputs.network.DeviceDot1xArgs | undefined>;
    ethernetOverrides?: pulumi.Input<pulumi.Input<inputs.network.DeviceEthernetOverrideArgs>[] | undefined>;
    lcm?: pulumi.Input<inputs.network.DeviceLcmArgs | undefined>;
    led?: pulumi.Input<inputs.network.DeviceLedArgs | undefined>;
    mac: pulumi.Input<string>;
    mgmtNetworkId?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    outlet?: pulumi.Input<inputs.network.DeviceOutletArgs | undefined>;
    portOverrides?: pulumi.Input<pulumi.Input<inputs.network.DevicePortOverrideArgs>[] | undefined>;
    radioTable?: pulumi.Input<pulumi.Input<inputs.network.DeviceRadioOverrideArgs>[] | undefined>;
    snmp?: pulumi.Input<inputs.network.DeviceSnmpArgs | undefined>;
    stp?: pulumi.Input<inputs.network.DeviceStpArgs | undefined>;
    switching?: pulumi.Input<inputs.network.DeviceSwitchingArgs | undefined>;
    vrrp?: pulumi.Input<inputs.network.DeviceVrrpArgs | undefined>;
}
