// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A UniFi controller-local (static) DNS record. Supported on gateways such as the UDM-SE. Maps to a controller static-dns object.
 */
export class DnsRecord extends pulumi.CustomResource {
    /**
     * Get an existing DnsRecord resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DnsRecord {
        return new DnsRecord(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:DnsRecord';

    /**
     * Returns true if the given object is an instance of DnsRecord.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsRecord {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsRecord.__pulumiType;
    }

    declare public /*out*/ readonly dnsRecordId: pulumi.Output<string>;
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly key: pulumi.Output<string>;
    declare public readonly port: pulumi.Output<number | undefined>;
    declare public readonly priority: pulumi.Output<number | undefined>;
    declare public readonly recordType: pulumi.Output<string>;
    declare public readonly ttl: pulumi.Output<number | undefined>;
    declare public readonly value: pulumi.Output<string>;
    declare public readonly weight: pulumi.Output<number | undefined>;

    /**
     * Create a DnsRecord resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsRecordArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.recordType === undefined && !opts.urn) {
                throw new Error("Missing required property 'recordType'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["key"] = args?.key;
            resourceInputs["port"] = args?.port;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["recordType"] = args?.recordType;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["value"] = args?.value;
            resourceInputs["weight"] = args?.weight;
            resourceInputs["dnsRecordId"] = undefined /*out*/;
        } else {
            resourceInputs["dnsRecordId"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["priority"] = undefined /*out*/;
            resourceInputs["recordType"] = undefined /*out*/;
            resourceInputs["ttl"] = undefined /*out*/;
            resourceInputs["value"] = undefined /*out*/;
            resourceInputs["weight"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsRecord.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DnsRecord resource.
 */
export interface DnsRecordArgs {
    enabled?: pulumi.Input<boolean | undefined>;
    key: pulumi.Input<string>;
    port?: pulumi.Input<number | undefined>;
    priority?: pulumi.Input<number | undefined>;
    recordType: pulumi.Input<string>;
    ttl?: pulumi.Input<number | undefined>;
    value: pulumi.Input<string>;
    weight?: pulumi.Input<number | undefined>;
}
