// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

/**
 * A classic (per-ruleset) UniFi firewall rule. Rules are evaluated in order within a ruleset, controlled by ruleIndex. Use firewall groups, networks, addresses, ports and connection-state matching to permit or block traffic. Match selectors are grouped into nested objects (protocolMatch, source, destination, connectionState).
 */
export class FirewallRule extends pulumi.CustomResource {
    /**
     * Get an existing FirewallRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): FirewallRule {
        return new FirewallRule(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:FirewallRule';

    /**
     * Returns true if the given object is an instance of FirewallRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FirewallRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FirewallRule.__pulumiType;
    }

    /**
     * Action taken on matching traffic: accept | drop | reject.
     */
    declare public readonly action: pulumi.Output<enums.network.FirewallRuleAction | undefined>;
    /**
     * ConnectionState groups the conntrack-state match toggles.
     */
    declare public readonly connectionState: pulumi.Output<outputs.network.FirewallRuleConnectionState | undefined>;
    /**
     * Destination groups the destination-side match selectors.
     */
    declare public readonly destination: pulumi.Output<outputs.network.FirewallRuleDestination | undefined>;
    /**
     * Enabled controls whether the rule is active. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * FirewallRuleId is the controller-assigned identifier (the UniFi `_id`).
     */
    declare public /*out*/ readonly firewallRuleId: pulumi.Output<string>;
    /**
     * IpSec matches on IPsec encapsulation: match-ipsec | match-none.
     */
    declare public readonly ipSec: pulumi.Output<enums.network.FirewallRuleIpSec | undefined>;
    /**
     * Logging enables logging of packets that match this rule.
     */
    declare public readonly logging: pulumi.Output<boolean | undefined>;
    /**
     * Name of the firewall rule (1-128 characters).
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * ProtocolMatch groups the protocol / ICMP-type match selectors.
     */
    declare public readonly protocolMatch: pulumi.Output<outputs.network.FirewallRuleProtocolMatch | undefined>;
    /**
     * RuleIndex is the ordering index of the rule within its ruleset. Must be >= 2000 and < 3000, or >= 4000 and < 5000.
     */
    declare public readonly ruleIndex: pulumi.Output<number>;
    /**
     * Ruleset the rule belongs to, from the perspective of the security gateway: WAN_IN | WAN_OUT | WAN_LOCAL | LAN_IN | LAN_OUT | LAN_LOCAL | GUEST_IN | GUEST_OUT | GUEST_LOCAL | WANv6_IN | WANv6_OUT | WANv6_LOCAL | LANv6_IN | LANv6_OUT | LANv6_LOCAL | GUESTv6_IN | GUESTv6_OUT | GUESTv6_LOCAL.
     */
    declare public readonly ruleset: pulumi.Output<string | undefined>;
    /**
     * SettingPreference controls whether the rule uses automatic or manual settings: auto | manual.
     */
    declare public readonly settingPreference: pulumi.Output<enums.network.FirewallRuleSettingPreference | undefined>;
    /**
     * Source groups the source-side match selectors.
     */
    declare public readonly source: pulumi.Output<outputs.network.FirewallRuleSource | undefined>;

    /**
     * Create a FirewallRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FirewallRuleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.ruleIndex === undefined && !opts.urn) {
                throw new Error("Missing required property 'ruleIndex'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["connectionState"] = args?.connectionState;
            resourceInputs["destination"] = args?.destination;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["ipSec"] = args?.ipSec;
            resourceInputs["logging"] = args?.logging;
            resourceInputs["name"] = args?.name;
            resourceInputs["protocolMatch"] = args?.protocolMatch;
            resourceInputs["ruleIndex"] = args?.ruleIndex;
            resourceInputs["ruleset"] = args?.ruleset;
            resourceInputs["settingPreference"] = args?.settingPreference;
            resourceInputs["source"] = args?.source;
            resourceInputs["firewallRuleId"] = undefined /*out*/;
        } else {
            resourceInputs["action"] = undefined /*out*/;
            resourceInputs["connectionState"] = undefined /*out*/;
            resourceInputs["destination"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["firewallRuleId"] = undefined /*out*/;
            resourceInputs["ipSec"] = undefined /*out*/;
            resourceInputs["logging"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["protocolMatch"] = undefined /*out*/;
            resourceInputs["ruleIndex"] = undefined /*out*/;
            resourceInputs["ruleset"] = undefined /*out*/;
            resourceInputs["settingPreference"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FirewallRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a FirewallRule resource.
 */
export interface FirewallRuleArgs {
    /**
     * Action taken on matching traffic: accept | drop | reject.
     */
    action?: pulumi.Input<enums.network.FirewallRuleAction | undefined>;
    /**
     * ConnectionState groups the conntrack-state match toggles.
     */
    connectionState?: pulumi.Input<inputs.network.FirewallRuleConnectionStateArgs | undefined>;
    /**
     * Destination groups the destination-side match selectors.
     */
    destination?: pulumi.Input<inputs.network.FirewallRuleDestinationArgs | undefined>;
    /**
     * Enabled controls whether the rule is active. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * IpSec matches on IPsec encapsulation: match-ipsec | match-none.
     */
    ipSec?: pulumi.Input<enums.network.FirewallRuleIpSec | undefined>;
    /**
     * Logging enables logging of packets that match this rule.
     */
    logging?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the firewall rule (1-128 characters).
     */
    name: pulumi.Input<string>;
    /**
     * ProtocolMatch groups the protocol / ICMP-type match selectors.
     */
    protocolMatch?: pulumi.Input<inputs.network.FirewallRuleProtocolMatchArgs | undefined>;
    /**
     * RuleIndex is the ordering index of the rule within its ruleset. Must be >= 2000 and < 3000, or >= 4000 and < 5000.
     */
    ruleIndex: pulumi.Input<number>;
    /**
     * Ruleset the rule belongs to, from the perspective of the security gateway: WAN_IN | WAN_OUT | WAN_LOCAL | LAN_IN | LAN_OUT | LAN_LOCAL | GUEST_IN | GUEST_OUT | GUEST_LOCAL | WANv6_IN | WANv6_OUT | WANv6_LOCAL | LANv6_IN | LANv6_OUT | LANv6_LOCAL | GUESTv6_IN | GUESTv6_OUT | GUESTv6_LOCAL.
     */
    ruleset?: pulumi.Input<string | undefined>;
    /**
     * SettingPreference controls whether the rule uses automatic or manual settings: auto | manual.
     */
    settingPreference?: pulumi.Input<enums.network.FirewallRuleSettingPreference | undefined>;
    /**
     * Source groups the source-side match selectors.
     */
    source?: pulumi.Input<inputs.network.FirewallRuleSourceArgs | undefined>;
}
