// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * A classic (per-ruleset) UniFi firewall rule. Rules are evaluated in order within a ruleset, controlled by ruleIndex. Use firewall groups, networks, addresses, ports and connection-state matching to permit or block traffic. Match selectors are grouped into nested objects (protocolMatch, source, destination, connectionState).
 */
export class FirewallRule extends pulumi.CustomResource {
    /**
     * Get an existing FirewallRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): FirewallRule {
        return new FirewallRule(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:FirewallRule';

    /**
     * Returns true if the given object is an instance of FirewallRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FirewallRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FirewallRule.__pulumiType;
    }

    declare public readonly action: pulumi.Output<string | undefined>;
    declare public readonly connectionState: pulumi.Output<outputs.network.FirewallRuleConnectionState | undefined>;
    declare public readonly destination: pulumi.Output<outputs.network.FirewallRuleDestination | undefined>;
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly firewallRuleId: pulumi.Output<string>;
    declare public readonly ipSec: pulumi.Output<string | undefined>;
    declare public readonly logging: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly protocolMatch: pulumi.Output<outputs.network.FirewallRuleProtocolMatch | undefined>;
    declare public readonly ruleIndex: pulumi.Output<number>;
    declare public readonly ruleset: pulumi.Output<string | undefined>;
    declare public readonly settingPreference: pulumi.Output<string | undefined>;
    declare public readonly source: pulumi.Output<outputs.network.FirewallRuleSource | undefined>;

    /**
     * Create a FirewallRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FirewallRuleArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.ruleIndex === undefined && !opts.urn) {
                throw new Error("Missing required property 'ruleIndex'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["connectionState"] = args?.connectionState;
            resourceInputs["destination"] = args?.destination;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["ipSec"] = args?.ipSec;
            resourceInputs["logging"] = args?.logging;
            resourceInputs["name"] = args?.name;
            resourceInputs["protocolMatch"] = args?.protocolMatch;
            resourceInputs["ruleIndex"] = args?.ruleIndex;
            resourceInputs["ruleset"] = args?.ruleset;
            resourceInputs["settingPreference"] = args?.settingPreference;
            resourceInputs["source"] = args?.source;
            resourceInputs["firewallRuleId"] = undefined /*out*/;
        } else {
            resourceInputs["action"] = undefined /*out*/;
            resourceInputs["connectionState"] = undefined /*out*/;
            resourceInputs["destination"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["firewallRuleId"] = undefined /*out*/;
            resourceInputs["ipSec"] = undefined /*out*/;
            resourceInputs["logging"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["protocolMatch"] = undefined /*out*/;
            resourceInputs["ruleIndex"] = undefined /*out*/;
            resourceInputs["ruleset"] = undefined /*out*/;
            resourceInputs["settingPreference"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FirewallRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a FirewallRule resource.
 */
export interface FirewallRuleArgs {
    action?: pulumi.Input<string | undefined>;
    connectionState?: pulumi.Input<inputs.network.FirewallRuleConnectionStateArgs | undefined>;
    destination?: pulumi.Input<inputs.network.FirewallRuleDestinationArgs | undefined>;
    enabled?: pulumi.Input<boolean | undefined>;
    ipSec?: pulumi.Input<string | undefined>;
    logging?: pulumi.Input<boolean | undefined>;
    name: pulumi.Input<string>;
    protocolMatch?: pulumi.Input<inputs.network.FirewallRuleProtocolMatchArgs | undefined>;
    ruleIndex: pulumi.Input<number>;
    ruleset?: pulumi.Input<string | undefined>;
    settingPreference?: pulumi.Input<string | undefined>;
    source?: pulumi.Input<inputs.network.FirewallRuleSourceArgs | undefined>;
}
