// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * A UniFi zone-based firewall policy (the Zone-Based Firewall feature on current UDM/UDM-SE/UXG firmware). Each policy matches traffic flowing from a source zone to a destination zone and applies an action. This resource requires a controller with the zone-based firewall enabled; it is not available on older controllers that still use the legacy firewall rule list.
 */
export class FirewallZonePolicy extends pulumi.CustomResource {
    /**
     * Get an existing FirewallZonePolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): FirewallZonePolicy {
        return new FirewallZonePolicy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:FirewallZonePolicy';

    /**
     * Returns true if the given object is an instance of FirewallZonePolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FirewallZonePolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FirewallZonePolicy.__pulumiType;
    }

    declare public readonly action: pulumi.Output<string>;
    declare public readonly createAllowRespond: pulumi.Output<boolean | undefined>;
    declare public readonly description: pulumi.Output<string | undefined>;
    declare public readonly destination: pulumi.Output<outputs.network.FirewallZonePolicyDestinationArgs>;
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly firewallZonePolicyId: pulumi.Output<string>;
    declare public readonly index: pulumi.Output<number | undefined>;
    declare public readonly logging: pulumi.Output<boolean | undefined>;
    declare public readonly matching: pulumi.Output<outputs.network.FirewallZonePolicyMatchingArgs | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly schedule: pulumi.Output<outputs.network.FirewallZonePolicyScheduleArgs | undefined>;
    declare public readonly source: pulumi.Output<outputs.network.FirewallZonePolicySourceArgs>;

    /**
     * Create a FirewallZonePolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FirewallZonePolicyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.action === undefined && !opts.urn) {
                throw new Error("Missing required property 'action'");
            }
            if (args?.destination === undefined && !opts.urn) {
                throw new Error("Missing required property 'destination'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.source === undefined && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["createAllowRespond"] = args?.createAllowRespond;
            resourceInputs["description"] = args?.description;
            resourceInputs["destination"] = args?.destination;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["index"] = args?.index;
            resourceInputs["logging"] = args?.logging;
            resourceInputs["matching"] = args?.matching;
            resourceInputs["name"] = args?.name;
            resourceInputs["schedule"] = args?.schedule;
            resourceInputs["source"] = args?.source;
            resourceInputs["firewallZonePolicyId"] = undefined /*out*/;
        } else {
            resourceInputs["action"] = undefined /*out*/;
            resourceInputs["createAllowRespond"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["destination"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["firewallZonePolicyId"] = undefined /*out*/;
            resourceInputs["index"] = undefined /*out*/;
            resourceInputs["logging"] = undefined /*out*/;
            resourceInputs["matching"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["schedule"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FirewallZonePolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a FirewallZonePolicy resource.
 */
export interface FirewallZonePolicyArgs {
    action: pulumi.Input<string>;
    createAllowRespond?: pulumi.Input<boolean | undefined>;
    description?: pulumi.Input<string | undefined>;
    destination: pulumi.Input<inputs.network.FirewallZonePolicyDestinationArgsArgs>;
    enabled?: pulumi.Input<boolean | undefined>;
    index?: pulumi.Input<number | undefined>;
    logging?: pulumi.Input<boolean | undefined>;
    matching?: pulumi.Input<inputs.network.FirewallZonePolicyMatchingArgsArgs | undefined>;
    name: pulumi.Input<string>;
    schedule?: pulumi.Input<inputs.network.FirewallZonePolicyScheduleArgsArgs | undefined>;
    source: pulumi.Input<inputs.network.FirewallZonePolicySourceArgsArgs>;
}
