// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * A UniFi port-forwarding (destination NAT) rule. Forwards traffic arriving on a WAN port (dstPort) to an internal host (fwd) and port (fwdPort).
 */
export class PortForward extends pulumi.CustomResource {
    /**
     * Get an existing PortForward resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PortForward {
        return new PortForward(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:PortForward';

    /**
     * Returns true if the given object is an instance of PortForward.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PortForward {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PortForward.__pulumiType;
    }

    declare public readonly destinationIp: pulumi.Output<string | undefined>;
    declare public readonly destinationIps: pulumi.Output<outputs.network.PortForwardDestinationIp[] | undefined>;
    declare public readonly dstPort: pulumi.Output<string | undefined>;
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly fwd: pulumi.Output<string | undefined>;
    declare public readonly fwdPort: pulumi.Output<string | undefined>;
    declare public readonly log: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string | undefined>;
    declare public readonly pfwdInterface: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly portForwardId: pulumi.Output<string>;
    declare public readonly proto: pulumi.Output<string | undefined>;
    declare public readonly src: pulumi.Output<string | undefined>;
    declare public readonly srcFirewallGroupId: pulumi.Output<string | undefined>;
    declare public readonly srcLimitingEnabled: pulumi.Output<boolean | undefined>;
    declare public readonly srcLimitingType: pulumi.Output<string | undefined>;

    /**
     * Create a PortForward resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PortForwardArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["destinationIp"] = args?.destinationIp;
            resourceInputs["destinationIps"] = args?.destinationIps;
            resourceInputs["dstPort"] = args?.dstPort;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["fwd"] = args?.fwd;
            resourceInputs["fwdPort"] = args?.fwdPort;
            resourceInputs["log"] = args?.log;
            resourceInputs["name"] = args?.name;
            resourceInputs["pfwdInterface"] = args?.pfwdInterface;
            resourceInputs["proto"] = args?.proto;
            resourceInputs["src"] = args?.src;
            resourceInputs["srcFirewallGroupId"] = args?.srcFirewallGroupId;
            resourceInputs["srcLimitingEnabled"] = args?.srcLimitingEnabled;
            resourceInputs["srcLimitingType"] = args?.srcLimitingType;
            resourceInputs["portForwardId"] = undefined /*out*/;
        } else {
            resourceInputs["destinationIp"] = undefined /*out*/;
            resourceInputs["destinationIps"] = undefined /*out*/;
            resourceInputs["dstPort"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["fwd"] = undefined /*out*/;
            resourceInputs["fwdPort"] = undefined /*out*/;
            resourceInputs["log"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["pfwdInterface"] = undefined /*out*/;
            resourceInputs["portForwardId"] = undefined /*out*/;
            resourceInputs["proto"] = undefined /*out*/;
            resourceInputs["src"] = undefined /*out*/;
            resourceInputs["srcFirewallGroupId"] = undefined /*out*/;
            resourceInputs["srcLimitingEnabled"] = undefined /*out*/;
            resourceInputs["srcLimitingType"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PortForward.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PortForward resource.
 */
export interface PortForwardArgs {
    destinationIp?: pulumi.Input<string | undefined>;
    destinationIps?: pulumi.Input<pulumi.Input<inputs.network.PortForwardDestinationIpArgs>[] | undefined>;
    dstPort?: pulumi.Input<string | undefined>;
    enabled?: pulumi.Input<boolean | undefined>;
    fwd?: pulumi.Input<string | undefined>;
    fwdPort?: pulumi.Input<string | undefined>;
    log?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
    pfwdInterface?: pulumi.Input<string | undefined>;
    proto?: pulumi.Input<string | undefined>;
    src?: pulumi.Input<string | undefined>;
    srcFirewallGroupId?: pulumi.Input<string | undefined>;
    srcLimitingEnabled?: pulumi.Input<boolean | undefined>;
    srcLimitingType?: pulumi.Input<string | undefined>;
}
