// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

/**
 * A UniFi port-forwarding (destination NAT) rule. Forwards traffic arriving on a WAN port (dstPort) to an internal host (fwd) and port (fwdPort).
 */
export class PortForward extends pulumi.CustomResource {
    /**
     * Get an existing PortForward resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PortForward {
        return new PortForward(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:PortForward';

    /**
     * Returns true if the given object is an instance of PortForward.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PortForward {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PortForward.__pulumiType;
    }

    /**
     * DestinationIp is the public/destination IPv4 address this rule matches, or "any".
     */
    declare public readonly destinationIp: pulumi.Output<string | undefined>;
    /**
     * DestinationIps maps destination IPs to specific WAN interfaces for multi-WAN setups.
     */
    declare public readonly destinationIps: pulumi.Output<outputs.network.PortForwardDestinationIp[] | undefined>;
    /**
     * DstPort is the external/WAN port traffic arrives ON, i.e. forwarded FROM (single port or range).
     */
    declare public readonly dstPort: pulumi.Output<string | undefined>;
    /**
     * Enabled controls whether the rule is active. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Fwd is the internal IPv4 address to forward traffic to.
     */
    declare public readonly fwd: pulumi.Output<string | undefined>;
    /**
     * FwdPort is the internal destination port traffic is forwarded TO (single port or range).
     */
    declare public readonly fwdPort: pulumi.Output<string | undefined>;
    /**
     * Log enables logging of forwarded traffic. Defaults to false.
     */
    declare public readonly log: pulumi.Output<boolean | undefined>;
    /**
     * Name of the port-forwarding rule (1-128 characters).
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * PfwdInterface selects the inbound WAN interface: wan | wan2 | both | all.
     */
    declare public readonly pfwdInterface: pulumi.Output<string | undefined>;
    /**
     * PortForwardId is the controller-assigned identifier (the UniFi `_id`).
     */
    declare public /*out*/ readonly portForwardId: pulumi.Output<string>;
    /**
     * Proto selects the matched protocol: tcp_udp | tcp | udp. Defaults to "tcp_udp".
     */
    declare public readonly proto: pulumi.Output<enums.network.PortForwardProtocol | undefined>;
    /**
     * Src restricts the source address: a single IPv4, range, CIDR, negation (!addr), or "any". Defaults to "any".
     */
    declare public readonly src: pulumi.Output<string | undefined>;
    /**
     * SrcFirewallGroupId references a firewall group used to restrict the source (when srcLimitingType=firewall_group).
     */
    declare public readonly srcFirewallGroupId: pulumi.Output<string | undefined>;
    /**
     * SrcLimitingEnabled enables restricting the rule by source address or firewall group.
     */
    declare public readonly srcLimitingEnabled: pulumi.Output<boolean | undefined>;
    /**
     * SrcLimitingType selects how the source is limited: ip | firewall_group.
     */
    declare public readonly srcLimitingType: pulumi.Output<string | undefined>;

    /**
     * Create a PortForward resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PortForwardArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["destinationIp"] = args?.destinationIp;
            resourceInputs["destinationIps"] = args?.destinationIps;
            resourceInputs["dstPort"] = args?.dstPort;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["fwd"] = args?.fwd;
            resourceInputs["fwdPort"] = args?.fwdPort;
            resourceInputs["log"] = args?.log;
            resourceInputs["name"] = args?.name;
            resourceInputs["pfwdInterface"] = args?.pfwdInterface;
            resourceInputs["proto"] = (args?.proto) ?? "tcp_udp";
            resourceInputs["src"] = (args?.src) ?? "any";
            resourceInputs["srcFirewallGroupId"] = args?.srcFirewallGroupId;
            resourceInputs["srcLimitingEnabled"] = args?.srcLimitingEnabled;
            resourceInputs["srcLimitingType"] = args?.srcLimitingType;
            resourceInputs["portForwardId"] = undefined /*out*/;
        } else {
            resourceInputs["destinationIp"] = undefined /*out*/;
            resourceInputs["destinationIps"] = undefined /*out*/;
            resourceInputs["dstPort"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["fwd"] = undefined /*out*/;
            resourceInputs["fwdPort"] = undefined /*out*/;
            resourceInputs["log"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["pfwdInterface"] = undefined /*out*/;
            resourceInputs["portForwardId"] = undefined /*out*/;
            resourceInputs["proto"] = undefined /*out*/;
            resourceInputs["src"] = undefined /*out*/;
            resourceInputs["srcFirewallGroupId"] = undefined /*out*/;
            resourceInputs["srcLimitingEnabled"] = undefined /*out*/;
            resourceInputs["srcLimitingType"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PortForward.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PortForward resource.
 */
export interface PortForwardArgs {
    /**
     * DestinationIp is the public/destination IPv4 address this rule matches, or "any".
     */
    destinationIp?: pulumi.Input<string | undefined>;
    /**
     * DestinationIps maps destination IPs to specific WAN interfaces for multi-WAN setups.
     */
    destinationIps?: pulumi.Input<pulumi.Input<inputs.network.PortForwardDestinationIpArgs>[] | undefined>;
    /**
     * DstPort is the external/WAN port traffic arrives ON, i.e. forwarded FROM (single port or range).
     */
    dstPort?: pulumi.Input<string | undefined>;
    /**
     * Enabled controls whether the rule is active. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Fwd is the internal IPv4 address to forward traffic to.
     */
    fwd?: pulumi.Input<string | undefined>;
    /**
     * FwdPort is the internal destination port traffic is forwarded TO (single port or range).
     */
    fwdPort?: pulumi.Input<string | undefined>;
    /**
     * Log enables logging of forwarded traffic. Defaults to false.
     */
    log?: pulumi.Input<boolean | undefined>;
    /**
     * Name of the port-forwarding rule (1-128 characters).
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * PfwdInterface selects the inbound WAN interface: wan | wan2 | both | all.
     */
    pfwdInterface?: pulumi.Input<string | undefined>;
    /**
     * Proto selects the matched protocol: tcp_udp | tcp | udp. Defaults to "tcp_udp".
     */
    proto?: pulumi.Input<enums.network.PortForwardProtocol | undefined>;
    /**
     * Src restricts the source address: a single IPv4, range, CIDR, negation (!addr), or "any". Defaults to "any".
     */
    src?: pulumi.Input<string | undefined>;
    /**
     * SrcFirewallGroupId references a firewall group used to restrict the source (when srcLimitingType=firewall_group).
     */
    srcFirewallGroupId?: pulumi.Input<string | undefined>;
    /**
     * SrcLimitingEnabled enables restricting the rule by source address or firewall group.
     */
    srcLimitingEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * SrcLimitingType selects how the source is limited: ip | firewall_group.
     */
    srcLimitingType?: pulumi.Input<string | undefined>;
}
