// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * A UniFi switch port profile (portconf). A reusable collection of port settings grouped into nested objects (vlan, link, stormControl, portSecurity, dot1x, lldpMed, egressRateLimit, priorityQueues) that can be applied to switch ports via a Device port override's portProfileId.
 */
export class PortProfile extends pulumi.CustomResource {
    /**
     * Get an existing PortProfile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PortProfile {
        return new PortProfile(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:PortProfile';

    /**
     * Returns true if the given object is an instance of PortProfile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PortProfile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PortProfile.__pulumiType;
    }

    /**
     * Dot1x groups the 802.1X PNAC settings.
     */
    declare public readonly dot1x: pulumi.Output<outputs.network.PortProfileDot1x | undefined>;
    /**
     * EgressRateLimit groups the outbound rate-limiting settings.
     */
    declare public readonly egressRateLimit: pulumi.Output<outputs.network.PortProfileEgressRateLimit | undefined>;
    /**
     * Isolation enables port isolation so devices on this profile cannot communicate with each other. Defaults to false.
     */
    declare public readonly isolation: pulumi.Output<boolean | undefined>;
    /**
     * Link groups the physical-layer link settings (speed/duplex/FEC).
     */
    declare public readonly link: pulumi.Output<outputs.network.PortProfileLink | undefined>;
    /**
     * LldpMed groups the LLDP-MED protocol toggles.
     */
    declare public readonly lldpMed: pulumi.Output<outputs.network.PortProfileLldpMed | undefined>;
    /**
     * Name is a descriptive name for the port profile.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * OpMode is the operation mode. Only "switch" is supported. Defaults to "switch".
     */
    declare public readonly opMode: pulumi.Output<string | undefined>;
    /**
     * PoeMode controls Power-over-Ethernet: auto | off (the values go-unifi accepts for a port profile). Per-port passthrough/pasv24 modes are set via a Device port override's poeMode, not here.
     */
    declare public readonly poeMode: pulumi.Output<string | undefined>;
    /**
     * PortKeepaliveEnabled enables port keepalive. Defaults to false.
     */
    declare public readonly portKeepaliveEnabled: pulumi.Output<boolean | undefined>;
    /**
     * PortProfileId is the controller-assigned identifier (the UniFi `_id`), referenced by a Device port override's portProfileId (portconf_id).
     */
    declare public /*out*/ readonly portProfileId: pulumi.Output<string>;
    /**
     * PortSecurity groups the MAC-based port-security settings.
     */
    declare public readonly portSecurity: pulumi.Output<outputs.network.PortProfilePortSecurity | undefined>;
    /**
     * PriorityQueues groups the QoS priority-queue levels.
     */
    declare public readonly priorityQueues: pulumi.Output<outputs.network.PortProfilePriorityQueues | undefined>;
    /**
     * SettingPreference controls config source: auto | manual.
     */
    declare public readonly settingPreference: pulumi.Output<string | undefined>;
    /**
     * StormControl groups the storm-control settings.
     */
    declare public readonly stormControl: pulumi.Output<outputs.network.PortProfileStormControl | undefined>;
    /**
     * StpPortMode enables Spanning Tree Protocol on the port. Defaults to true.
     */
    declare public readonly stpPortMode: pulumi.Output<boolean | undefined>;
    /**
     * Vlan groups the VLAN / forwarding settings.
     */
    declare public readonly vlan: pulumi.Output<outputs.network.PortProfileVlan | undefined>;

    /**
     * Create a PortProfile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PortProfileArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["dot1x"] = args?.dot1x;
            resourceInputs["egressRateLimit"] = args?.egressRateLimit;
            resourceInputs["isolation"] = args?.isolation;
            resourceInputs["link"] = args?.link;
            resourceInputs["lldpMed"] = args?.lldpMed;
            resourceInputs["name"] = args?.name;
            resourceInputs["opMode"] = args?.opMode;
            resourceInputs["poeMode"] = args?.poeMode;
            resourceInputs["portKeepaliveEnabled"] = args?.portKeepaliveEnabled;
            resourceInputs["portSecurity"] = args?.portSecurity;
            resourceInputs["priorityQueues"] = args?.priorityQueues;
            resourceInputs["settingPreference"] = args?.settingPreference;
            resourceInputs["stormControl"] = args?.stormControl;
            resourceInputs["stpPortMode"] = args?.stpPortMode;
            resourceInputs["vlan"] = args?.vlan;
            resourceInputs["portProfileId"] = undefined /*out*/;
        } else {
            resourceInputs["dot1x"] = undefined /*out*/;
            resourceInputs["egressRateLimit"] = undefined /*out*/;
            resourceInputs["isolation"] = undefined /*out*/;
            resourceInputs["link"] = undefined /*out*/;
            resourceInputs["lldpMed"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["opMode"] = undefined /*out*/;
            resourceInputs["poeMode"] = undefined /*out*/;
            resourceInputs["portKeepaliveEnabled"] = undefined /*out*/;
            resourceInputs["portProfileId"] = undefined /*out*/;
            resourceInputs["portSecurity"] = undefined /*out*/;
            resourceInputs["priorityQueues"] = undefined /*out*/;
            resourceInputs["settingPreference"] = undefined /*out*/;
            resourceInputs["stormControl"] = undefined /*out*/;
            resourceInputs["stpPortMode"] = undefined /*out*/;
            resourceInputs["vlan"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PortProfile.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PortProfile resource.
 */
export interface PortProfileArgs {
    /**
     * Dot1x groups the 802.1X PNAC settings.
     */
    dot1x?: pulumi.Input<inputs.network.PortProfileDot1xArgs | undefined>;
    /**
     * EgressRateLimit groups the outbound rate-limiting settings.
     */
    egressRateLimit?: pulumi.Input<inputs.network.PortProfileEgressRateLimitArgs | undefined>;
    /**
     * Isolation enables port isolation so devices on this profile cannot communicate with each other. Defaults to false.
     */
    isolation?: pulumi.Input<boolean | undefined>;
    /**
     * Link groups the physical-layer link settings (speed/duplex/FEC).
     */
    link?: pulumi.Input<inputs.network.PortProfileLinkArgs | undefined>;
    /**
     * LldpMed groups the LLDP-MED protocol toggles.
     */
    lldpMed?: pulumi.Input<inputs.network.PortProfileLldpMedArgs | undefined>;
    /**
     * Name is a descriptive name for the port profile.
     */
    name: pulumi.Input<string>;
    /**
     * OpMode is the operation mode. Only "switch" is supported. Defaults to "switch".
     */
    opMode?: pulumi.Input<string | undefined>;
    /**
     * PoeMode controls Power-over-Ethernet: auto | off (the values go-unifi accepts for a port profile). Per-port passthrough/pasv24 modes are set via a Device port override's poeMode, not here.
     */
    poeMode?: pulumi.Input<string | undefined>;
    /**
     * PortKeepaliveEnabled enables port keepalive. Defaults to false.
     */
    portKeepaliveEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * PortSecurity groups the MAC-based port-security settings.
     */
    portSecurity?: pulumi.Input<inputs.network.PortProfilePortSecurityArgs | undefined>;
    /**
     * PriorityQueues groups the QoS priority-queue levels.
     */
    priorityQueues?: pulumi.Input<inputs.network.PortProfilePriorityQueuesArgs | undefined>;
    /**
     * SettingPreference controls config source: auto | manual.
     */
    settingPreference?: pulumi.Input<string | undefined>;
    /**
     * StormControl groups the storm-control settings.
     */
    stormControl?: pulumi.Input<inputs.network.PortProfileStormControlArgs | undefined>;
    /**
     * StpPortMode enables Spanning Tree Protocol on the port. Defaults to true.
     */
    stpPortMode?: pulumi.Input<boolean | undefined>;
    /**
     * Vlan groups the VLAN / forwarding settings.
     */
    vlan?: pulumi.Input<inputs.network.PortProfileVlanArgs | undefined>;
}
