// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

/**
 * A UniFi static route. Maps to a controller routing object with type=static-route, directing traffic for a destination network via a next hop, an egress interface, or a blackhole.
 */
export class StaticRoute extends pulumi.CustomResource {
    /**
     * Get an existing StaticRoute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): StaticRoute {
        return new StaticRoute(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:StaticRoute';

    /**
     * Returns true if the given object is an instance of StaticRoute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StaticRoute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StaticRoute.__pulumiType;
    }

    /**
     * Distance is the administrative distance / metric of the route (1-255).
     */
    declare public readonly distance: pulumi.Output<number | undefined>;
    /**
     * Enabled controls whether the route is active. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * GatewayDevice is the MAC address of the gateway device that hosts the route.
     */
    declare public readonly gatewayDevice: pulumi.Output<string | undefined>;
    /**
     * GatewayType selects which gateway handles the route: default | switch.
     */
    declare public readonly gatewayType: pulumi.Output<enums.network.StaticRouteGatewayType | undefined>;
    /**
     * Interface is the egress interface when staticRouteType=interface-route: WAN1 | WAN2 | a network ID.
     */
    declare public readonly interface: pulumi.Output<string | undefined>;
    /**
     * Name of the static route.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Network is the destination network in CIDR notation (IPv4 or IPv6), e.g. 10.0.0.0/24.
     */
    declare public readonly network: pulumi.Output<string>;
    /**
     * Nexthop is the next-hop IP address (required when staticRouteType=nexthop-route).
     */
    declare public readonly nexthop: pulumi.Output<string | undefined>;
    /**
     * StaticRouteId is the controller-assigned identifier (the UniFi `_id`).
     */
    declare public /*out*/ readonly staticRouteId: pulumi.Output<string>;
    /**
     * StaticRouteType selects the route kind: nexthop-route | interface-route | blackhole.
     */
    declare public readonly staticRouteType: pulumi.Output<enums.network.StaticRouteType>;

    /**
     * Create a StaticRoute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StaticRouteArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.network === undefined && !opts.urn) {
                throw new Error("Missing required property 'network'");
            }
            if (args?.staticRouteType === undefined && !opts.urn) {
                throw new Error("Missing required property 'staticRouteType'");
            }
            resourceInputs["distance"] = args?.distance;
            resourceInputs["enabled"] = (args?.enabled) ?? true;
            resourceInputs["gatewayDevice"] = args?.gatewayDevice;
            resourceInputs["gatewayType"] = args?.gatewayType;
            resourceInputs["interface"] = args?.interface;
            resourceInputs["name"] = args?.name;
            resourceInputs["network"] = args?.network;
            resourceInputs["nexthop"] = args?.nexthop;
            resourceInputs["staticRouteType"] = args?.staticRouteType;
            resourceInputs["staticRouteId"] = undefined /*out*/;
        } else {
            resourceInputs["distance"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["gatewayDevice"] = undefined /*out*/;
            resourceInputs["gatewayType"] = undefined /*out*/;
            resourceInputs["interface"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["network"] = undefined /*out*/;
            resourceInputs["nexthop"] = undefined /*out*/;
            resourceInputs["staticRouteId"] = undefined /*out*/;
            resourceInputs["staticRouteType"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StaticRoute.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a StaticRoute resource.
 */
export interface StaticRouteArgs {
    /**
     * Distance is the administrative distance / metric of the route (1-255).
     */
    distance?: pulumi.Input<number | undefined>;
    /**
     * Enabled controls whether the route is active. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * GatewayDevice is the MAC address of the gateway device that hosts the route.
     */
    gatewayDevice?: pulumi.Input<string | undefined>;
    /**
     * GatewayType selects which gateway handles the route: default | switch.
     */
    gatewayType?: pulumi.Input<enums.network.StaticRouteGatewayType | undefined>;
    /**
     * Interface is the egress interface when staticRouteType=interface-route: WAN1 | WAN2 | a network ID.
     */
    interface?: pulumi.Input<string | undefined>;
    /**
     * Name of the static route.
     */
    name: pulumi.Input<string>;
    /**
     * Network is the destination network in CIDR notation (IPv4 or IPv6), e.g. 10.0.0.0/24.
     */
    network: pulumi.Input<string>;
    /**
     * Nexthop is the next-hop IP address (required when staticRouteType=nexthop-route).
     */
    nexthop?: pulumi.Input<string | undefined>;
    /**
     * StaticRouteType selects the route kind: nexthop-route | interface-route | blackhole.
     */
    staticRouteType: pulumi.Input<enums.network.StaticRouteType>;
}
