// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A UniFi user group, applying per-client bandwidth (QoS rate) limits that can be assigned to clients.
 */
export class UserGroup extends pulumi.CustomResource {
    /**
     * Get an existing UserGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): UserGroup {
        return new UserGroup(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:UserGroup';

    /**
     * Returns true if the given object is an instance of UserGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserGroup.__pulumiType;
    }

    /**
     * Name of the user group.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * QosRateMaxDown is the maximum download rate in kbps. -1 means unlimited. Defaults to -1.
     */
    declare public readonly qosRateMaxDown: pulumi.Output<number | undefined>;
    /**
     * QosRateMaxUp is the maximum upload rate in kbps. -1 means unlimited. Defaults to -1.
     */
    declare public readonly qosRateMaxUp: pulumi.Output<number | undefined>;
    /**
     * UserGroupId is the controller-assigned identifier (the UniFi `_id`).
     */
    declare public /*out*/ readonly userGroupId: pulumi.Output<string>;

    /**
     * Create a UserGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserGroupArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["qosRateMaxDown"] = args?.qosRateMaxDown;
            resourceInputs["qosRateMaxUp"] = args?.qosRateMaxUp;
            resourceInputs["userGroupId"] = undefined /*out*/;
        } else {
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["qosRateMaxDown"] = undefined /*out*/;
            resourceInputs["qosRateMaxUp"] = undefined /*out*/;
            resourceInputs["userGroupId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UserGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a UserGroup resource.
 */
export interface UserGroupArgs {
    /**
     * Name of the user group.
     */
    name: pulumi.Input<string>;
    /**
     * QosRateMaxDown is the maximum download rate in kbps. -1 means unlimited. Defaults to -1.
     */
    qosRateMaxDown?: pulumi.Input<number | undefined>;
    /**
     * QosRateMaxUp is the maximum upload rate in kbps. -1 means unlimited. Defaults to -1.
     */
    qosRateMaxUp?: pulumi.Input<number | undefined>;
}
