// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A UniFi user (a known client / device). Maps to a controller user object keyed by MAC address. Creating this resource registers the client on the controller; deleting it removes the user record. Supports assigning a friendly name, user group, fixed IP, local DNS record, virtual network (VLAN) override, fixed access point, and blocking the client.
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    declare public readonly blocked: pulumi.Output<boolean | undefined>;
    declare public readonly devIdOverride: pulumi.Output<number | undefined>;
    declare public readonly fixedApEnabled: pulumi.Output<boolean | undefined>;
    declare public readonly fixedApMac: pulumi.Output<string | undefined>;
    declare public readonly fixedIp: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    declare public /*out*/ readonly ip: pulumi.Output<string>;
    declare public /*out*/ readonly lastSeen: pulumi.Output<number>;
    declare public readonly localDnsRecord: pulumi.Output<string | undefined>;
    declare public readonly localDnsRecordEnabled: pulumi.Output<boolean | undefined>;
    declare public readonly mac: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string | undefined>;
    declare public readonly networkId: pulumi.Output<string | undefined>;
    declare public readonly note: pulumi.Output<string | undefined>;
    declare public readonly useFixedIp: pulumi.Output<boolean | undefined>;
    declare public readonly userGroupId: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly userId: pulumi.Output<string>;
    declare public readonly virtualNetworkOverrideEnabled: pulumi.Output<boolean | undefined>;
    declare public readonly virtualNetworkOverrideId: pulumi.Output<string | undefined>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.mac === undefined && !opts.urn) {
                throw new Error("Missing required property 'mac'");
            }
            resourceInputs["blocked"] = args?.blocked;
            resourceInputs["devIdOverride"] = args?.devIdOverride;
            resourceInputs["fixedApEnabled"] = args?.fixedApEnabled;
            resourceInputs["fixedApMac"] = args?.fixedApMac;
            resourceInputs["fixedIp"] = args?.fixedIp;
            resourceInputs["localDnsRecord"] = args?.localDnsRecord;
            resourceInputs["localDnsRecordEnabled"] = args?.localDnsRecordEnabled;
            resourceInputs["mac"] = args?.mac;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkId"] = args?.networkId;
            resourceInputs["note"] = args?.note;
            resourceInputs["useFixedIp"] = args?.useFixedIp;
            resourceInputs["userGroupId"] = args?.userGroupId;
            resourceInputs["virtualNetworkOverrideEnabled"] = args?.virtualNetworkOverrideEnabled;
            resourceInputs["virtualNetworkOverrideId"] = args?.virtualNetworkOverrideId;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["lastSeen"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["blocked"] = undefined /*out*/;
            resourceInputs["devIdOverride"] = undefined /*out*/;
            resourceInputs["fixedApEnabled"] = undefined /*out*/;
            resourceInputs["fixedApMac"] = undefined /*out*/;
            resourceInputs["fixedIp"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["lastSeen"] = undefined /*out*/;
            resourceInputs["localDnsRecord"] = undefined /*out*/;
            resourceInputs["localDnsRecordEnabled"] = undefined /*out*/;
            resourceInputs["mac"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkId"] = undefined /*out*/;
            resourceInputs["note"] = undefined /*out*/;
            resourceInputs["useFixedIp"] = undefined /*out*/;
            resourceInputs["userGroupId"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["virtualNetworkOverrideEnabled"] = undefined /*out*/;
            resourceInputs["virtualNetworkOverrideId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    blocked?: pulumi.Input<boolean | undefined>;
    devIdOverride?: pulumi.Input<number | undefined>;
    fixedApEnabled?: pulumi.Input<boolean | undefined>;
    fixedApMac?: pulumi.Input<string | undefined>;
    fixedIp?: pulumi.Input<string | undefined>;
    localDnsRecord?: pulumi.Input<string | undefined>;
    localDnsRecordEnabled?: pulumi.Input<boolean | undefined>;
    mac: pulumi.Input<string>;
    name?: pulumi.Input<string | undefined>;
    networkId?: pulumi.Input<string | undefined>;
    note?: pulumi.Input<string | undefined>;
    useFixedIp?: pulumi.Input<boolean | undefined>;
    userGroupId?: pulumi.Input<string | undefined>;
    virtualNetworkOverrideEnabled?: pulumi.Input<boolean | undefined>;
    virtualNetworkOverrideId?: pulumi.Input<string | undefined>;
}
