// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A UniFi user (a known client / device). Maps to a controller user object keyed by MAC address. Creating this resource registers the client on the controller; deleting it removes the user record. Supports assigning a friendly name, user group, fixed IP, local DNS record, virtual network (VLAN) override, fixed access point, and blocking the client.
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * Blocked, when true, blocks this client from accessing the network.
     */
    declare public readonly blocked: pulumi.Output<boolean | undefined>;
    /**
     * DevIdOverride overrides the detected device fingerprint (device type id). 0 clears the override.
     */
    declare public readonly devIdOverride: pulumi.Output<number | undefined>;
    /**
     * FixedApEnabled toggles pinning the client to a fixed access point. Defaults to true when FixedApMac is set.
     */
    declare public readonly fixedApEnabled: pulumi.Output<boolean | undefined>;
    /**
     * FixedApMac is the MAC address of the access point the client is pinned to.
     */
    declare public readonly fixedApMac: pulumi.Output<string | undefined>;
    /**
     * FixedIp is a static IPv4 address to assign to this client. Setting it enables UseFixedIp.
     */
    declare public readonly fixedIp: pulumi.Output<string | undefined>;
    /**
     * Hostname is the hostname the controller has observed for the client.
     */
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    /**
     * Ip is the last-known IP address of the client (best-effort; may be empty).
     */
    declare public /*out*/ readonly ip: pulumi.Output<string>;
    /**
     * LastSeen is the Unix timestamp (seconds) the client was last seen.
     */
    declare public /*out*/ readonly lastSeen: pulumi.Output<number>;
    /**
     * LocalDnsRecord is a local DNS hostname resolving to this client. Setting it enables LocalDnsRecordEnabled.
     */
    declare public readonly localDnsRecord: pulumi.Output<string | undefined>;
    /**
     * LocalDnsRecordEnabled toggles publishing the LocalDnsRecord. Defaults to true when LocalDnsRecord is set.
     */
    declare public readonly localDnsRecordEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Mac is the client MAC address (e.g. "00:11:22:33:44:55"). It is the unique key used to register and look up the client.
     */
    declare public readonly mac: pulumi.Output<string>;
    /**
     * Name is a friendly name for the client.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * NetworkId is the ID of the network the fixed IP is assigned from.
     */
    declare public readonly networkId: pulumi.Output<string | undefined>;
    /**
     * Note is free-form text stored alongside the client.
     */
    declare public readonly note: pulumi.Output<string | undefined>;
    /**
     * UseFixedIp toggles assigning the FixedIp to the client. Defaults to true when FixedIp is set.
     */
    declare public readonly useFixedIp: pulumi.Output<boolean | undefined>;
    /**
     * UserGroupId is the ID of the user group (bandwidth profile) this client belongs to.
     */
    declare public readonly userGroupId: pulumi.Output<string | undefined>;
    /**
     * UserId is the controller-assigned identifier (the UniFi `_id`).
     */
    declare public /*out*/ readonly userId: pulumi.Output<string>;
    /**
     * VirtualNetworkOverrideEnabled toggles overriding the client's virtual network (VLAN). Defaults to true when VirtualNetworkOverrideId is set.
     */
    declare public readonly virtualNetworkOverrideEnabled: pulumi.Output<boolean | undefined>;
    /**
     * VirtualNetworkOverrideId is the ID of the virtual network (VLAN) the client is pinned to.
     */
    declare public readonly virtualNetworkOverrideId: pulumi.Output<string | undefined>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.mac === undefined && !opts.urn) {
                throw new Error("Missing required property 'mac'");
            }
            resourceInputs["blocked"] = args?.blocked;
            resourceInputs["devIdOverride"] = args?.devIdOverride;
            resourceInputs["fixedApEnabled"] = args?.fixedApEnabled;
            resourceInputs["fixedApMac"] = args?.fixedApMac;
            resourceInputs["fixedIp"] = args?.fixedIp;
            resourceInputs["localDnsRecord"] = args?.localDnsRecord;
            resourceInputs["localDnsRecordEnabled"] = args?.localDnsRecordEnabled;
            resourceInputs["mac"] = args?.mac;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkId"] = args?.networkId;
            resourceInputs["note"] = args?.note;
            resourceInputs["useFixedIp"] = args?.useFixedIp;
            resourceInputs["userGroupId"] = args?.userGroupId;
            resourceInputs["virtualNetworkOverrideEnabled"] = args?.virtualNetworkOverrideEnabled;
            resourceInputs["virtualNetworkOverrideId"] = args?.virtualNetworkOverrideId;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["lastSeen"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["blocked"] = undefined /*out*/;
            resourceInputs["devIdOverride"] = undefined /*out*/;
            resourceInputs["fixedApEnabled"] = undefined /*out*/;
            resourceInputs["fixedApMac"] = undefined /*out*/;
            resourceInputs["fixedIp"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["lastSeen"] = undefined /*out*/;
            resourceInputs["localDnsRecord"] = undefined /*out*/;
            resourceInputs["localDnsRecordEnabled"] = undefined /*out*/;
            resourceInputs["mac"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkId"] = undefined /*out*/;
            resourceInputs["note"] = undefined /*out*/;
            resourceInputs["useFixedIp"] = undefined /*out*/;
            resourceInputs["userGroupId"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["virtualNetworkOverrideEnabled"] = undefined /*out*/;
            resourceInputs["virtualNetworkOverrideId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["mac"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Blocked, when true, blocks this client from accessing the network.
     */
    blocked?: pulumi.Input<boolean | undefined>;
    /**
     * DevIdOverride overrides the detected device fingerprint (device type id). 0 clears the override.
     */
    devIdOverride?: pulumi.Input<number | undefined>;
    /**
     * FixedApEnabled toggles pinning the client to a fixed access point. Defaults to true when FixedApMac is set.
     */
    fixedApEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * FixedApMac is the MAC address of the access point the client is pinned to.
     */
    fixedApMac?: pulumi.Input<string | undefined>;
    /**
     * FixedIp is a static IPv4 address to assign to this client. Setting it enables UseFixedIp.
     */
    fixedIp?: pulumi.Input<string | undefined>;
    /**
     * LocalDnsRecord is a local DNS hostname resolving to this client. Setting it enables LocalDnsRecordEnabled.
     */
    localDnsRecord?: pulumi.Input<string | undefined>;
    /**
     * LocalDnsRecordEnabled toggles publishing the LocalDnsRecord. Defaults to true when LocalDnsRecord is set.
     */
    localDnsRecordEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Mac is the client MAC address (e.g. "00:11:22:33:44:55"). It is the unique key used to register and look up the client.
     */
    mac: pulumi.Input<string>;
    /**
     * Name is a friendly name for the client.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * NetworkId is the ID of the network the fixed IP is assigned from.
     */
    networkId?: pulumi.Input<string | undefined>;
    /**
     * Note is free-form text stored alongside the client.
     */
    note?: pulumi.Input<string | undefined>;
    /**
     * UseFixedIp toggles assigning the FixedIp to the client. Defaults to true when FixedIp is set.
     */
    useFixedIp?: pulumi.Input<boolean | undefined>;
    /**
     * UserGroupId is the ID of the user group (bandwidth profile) this client belongs to.
     */
    userGroupId?: pulumi.Input<string | undefined>;
    /**
     * VirtualNetworkOverrideEnabled toggles overriding the client's virtual network (VLAN). Defaults to true when VirtualNetworkOverrideId is set.
     */
    virtualNetworkOverrideEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * VirtualNetworkOverrideId is the ID of the virtual network (VLAN) the client is pinned to.
     */
    virtualNetworkOverrideId?: pulumi.Input<string | undefined>;
}
