// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Wlan extends pulumi.CustomResource {
    /**
     * Get an existing Wlan resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Wlan {
        return new Wlan(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:network:Wlan';

    /**
     * Returns true if the given object is an instance of Wlan.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Wlan {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Wlan.__pulumiType;
    }

    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly hideSsid: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly networkId: pulumi.Output<string>;
    declare public readonly passphrase: pulumi.Output<string | undefined>;
    declare public readonly security: pulumi.Output<string | undefined>;
    declare public readonly wlanGroupId: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly wlanId: pulumi.Output<string>;
    declare public readonly wpaMode: pulumi.Output<string | undefined>;

    /**
     * Create a Wlan resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WlanArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.networkId === undefined && !opts.urn) {
                throw new Error("Missing required property 'networkId'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["hideSsid"] = args?.hideSsid;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkId"] = args?.networkId;
            resourceInputs["passphrase"] = args?.passphrase ? pulumi.secret(args.passphrase) : undefined;
            resourceInputs["security"] = args?.security;
            resourceInputs["wlanGroupId"] = args?.wlanGroupId;
            resourceInputs["wpaMode"] = args?.wpaMode;
            resourceInputs["wlanId"] = undefined /*out*/;
        } else {
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["hideSsid"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networkId"] = undefined /*out*/;
            resourceInputs["passphrase"] = undefined /*out*/;
            resourceInputs["security"] = undefined /*out*/;
            resourceInputs["wlanGroupId"] = undefined /*out*/;
            resourceInputs["wlanId"] = undefined /*out*/;
            resourceInputs["wpaMode"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["passphrase"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Wlan.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Wlan resource.
 */
export interface WlanArgs {
    enabled?: pulumi.Input<boolean | undefined>;
    hideSsid?: pulumi.Input<boolean | undefined>;
    name: pulumi.Input<string>;
    networkId: pulumi.Input<string>;
    passphrase?: pulumi.Input<string | undefined>;
    security?: pulumi.Input<string | undefined>;
    wlanGroupId?: pulumi.Input<string | undefined>;
    wpaMode?: pulumi.Input<string | undefined>;
}
