// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'unifi';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * UniFi OS local API key. Preferred for headless automation. Mutually exclusive with username/password.
     */
    declare public readonly apiKey: pulumi.Output<string | undefined>;
    /**
     * Local admin password.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * UniFi site name (defaults to "default").
     */
    declare public readonly site: pulumi.Output<string | undefined>;
    /**
     * Password for unasUsername.
     */
    declare public readonly unasPassword: pulumi.Output<string | undefined>;
    /**
     * Base URL of the UNAS appliance hosting UniFi Drive, e.g. https://192.168.1.20. A SEPARATE host from `url`; required to manage `unifi:drive:*` resources.
     */
    declare public readonly unasUrl: pulumi.Output<string | undefined>;
    /**
     * Local UniFi OS admin username on the UNAS appliance (UniFi Drive has no API-key auth).
     */
    declare public readonly unasUsername: pulumi.Output<string | undefined>;
    /**
     * Base URL of the UniFi controller, e.g. https://192.168.1.1 (omit any /api suffix).
     */
    declare public readonly url: pulumi.Output<string | undefined>;
    /**
     * Local admin username. Use with password when not using an API key.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["apiKey"] = (args?.apiKey ? pulumi.secret(args.apiKey) : undefined) ?? utilities.getEnv("UNIFI_API_KEY");
            resourceInputs["insecureTls"] = pulumi.output((args?.insecureTls) ?? utilities.getEnvBoolean("UNIFI_INSECURE_TLS")).apply(JSON.stringify);
            resourceInputs["password"] = (args?.password ? pulumi.secret(args.password) : undefined) ?? utilities.getEnv("UNIFI_PASSWORD");
            resourceInputs["site"] = (args?.site) ?? (utilities.getEnv("UNIFI_SITE") || "default");
            resourceInputs["unasPassword"] = (args?.unasPassword ? pulumi.secret(args.unasPassword) : undefined) ?? utilities.getEnv("UNIFI_UNAS_PASSWORD");
            resourceInputs["unasUrl"] = (args?.unasUrl) ?? utilities.getEnv("UNIFI_UNAS_URL");
            resourceInputs["unasUsername"] = (args?.unasUsername) ?? utilities.getEnv("UNIFI_UNAS_USERNAME");
            resourceInputs["url"] = (args?.url) ?? utilities.getEnv("UNIFI_URL");
            resourceInputs["username"] = (args?.username) ?? utilities.getEnv("UNIFI_USERNAME");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey", "password", "unasPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * UniFi OS local API key. Preferred for headless automation. Mutually exclusive with username/password.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * Skip TLS certificate verification (for self-signed controller and UNAS certs).
     */
    insecureTls?: pulumi.Input<boolean | undefined>;
    /**
     * Local admin password.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * UniFi site name (defaults to "default").
     */
    site?: pulumi.Input<string | undefined>;
    /**
     * Password for unasUsername.
     */
    unasPassword?: pulumi.Input<string | undefined>;
    /**
     * Base URL of the UNAS appliance hosting UniFi Drive, e.g. https://192.168.1.20. A SEPARATE host from `url`; required to manage `unifi:drive:*` resources.
     */
    unasUrl?: pulumi.Input<string | undefined>;
    /**
     * Local UniFi OS admin username on the UNAS appliance (UniFi Drive has no API-key auth).
     */
    unasUsername?: pulumi.Input<string | undefined>;
    /**
     * Base URL of the UniFi controller, e.g. https://192.168.1.1 (omit any /api suffix).
     */
    url?: pulumi.Input<string | undefined>;
    /**
     * Local admin username. Use with password when not using an API key.
     */
    username?: pulumi.Input<string | undefined>;
}
